Script.Load("Data\\Script\\ModLoader\\ModLoader.lua")
Script.Load("Data\\Script\\InterfaceTools\\AutoScroll.lua")

if false then
	---@class CPPLMMMod
	---@field Active boolean
	local t = {Name = "", Description = "", MainmenuMod = true, UserRequestable = true}
end

ModLoaderMainmenu = {
	InitUICallbacks = {
		function()
			if XGUIEng.GetWidgetID("OptionsMenuCppLogic") == 0 then
				ModLoaderMainmenu.InitUI()
				ModLoaderMainmenu.Scroll:Setup()
				ModLoaderMainmenu.MonitorScroll:Setup()
			end
		end,
	},
	---@type CPPLAutoScroll<CPPLMMMod>
	Scroll = AutoScroll.Init("OptionsMenuCppLogic_ModListScroll", nil, nil, nil, true),
	---@type CPPLAutoScroll<CPPLMonitorInfo>
	MonitorScroll = AutoScroll.Init("OptionsMenu30_ResExtraScroll", "OptionsMenu30_ResExtraUp", "OptionsMenu30_ResExtraDown", "OptionsMenu30_ResExtraSliderBG", true),
}

ModLoaderMainmenu.Start = StartMenu.Start
ModLoaderMainmenu.S00_Update_VersionNumber = StartMenu.S00_Update_VersionNumber
---@diagnostic disable-next-line: duplicate-set-field
function StartMenu.Start(_StartVideoFlag)
	ModLoaderMainmenu.Start(_StartVideoFlag)
	StartMenu.Start = ModLoaderMainmenu.Start
	xpcall(function()
		ModLoaderMainmenu.LoadModpacks()
		ModLoaderMainmenu.LoadMainmenuModPacks()
		ModLoader.LoadSTTOverride("CppLogic_Mainmenu")
	end, CppLogic.API.Log)
end

---@diagnostic disable-next-line: duplicate-set-field
function StartMenu.S00_Update_VersionNumber()
	ModLoaderMainmenu.S00_Update_VersionNumber()
	for _, cb in ipairs(ModLoaderMainmenu.InitUICallbacks) do
		xpcall(cb, CppLogic.API.Log)
	end
	CppLogic.UI.WidgetSetUpdateManualFlag("StartMenu00_VersionNumber", true)
end

function ModLoaderMainmenu.Show()
	XGUIEng.ShowAllSubWidgets("Screens", 0)
	XGUIEng.ShowWidget("OptionsMenuCppLogic", 1)
	ModLoaderMainmenu.Scroll:SetDataToScrollOver(ModLoaderMainmenu.ModPacks)
end

function ModLoaderMainmenu.LoadModpacks()
	---@type CPPLMMMod[]
	ModLoaderMainmenu.ModPacks = {}
	for _, m in ipairs(CppLogic.ModLoader.GetModpacks()) do
		local mp = CppLogic.ModLoader.GetModpackInfo(m)
		if type(mp) == "table" and (mp.UserRequestable or mp.MainmenuMod) then
			table.insert(ModLoaderMainmenu.ModPacks, {Name = mp.Name,
				Active = false,
				Description = mp.Description,
				MainmenuMod = mp.MainmenuMod,
				UserRequestable = mp.UserRequestable,
			})
		end
	end
	local str = GDB.GetString("CppLogic\\UserRequestedMods")
	if str and str ~= "" then
		for _, m in ipairs(ModLoader.LoadModList(str)) do
			for _, mp in ipairs(ModLoaderMainmenu.ModPacks) do
				if mp.Name == m then
					mp.Active = true
				end
			end
		end
	end
	ModLoaderMainmenu.StoreUserRequestedModpacks() -- clear out no longer existing modpacks
end

function ModLoaderMainmenu.StoreUserRequestedModpacks()
	local s = ""
	for _, mp in ipairs(ModLoaderMainmenu.ModPacks) do
		if mp.Active then
			s = s .. mp.Name .. ";"
		end
	end
	GDB.SetString("CppLogic\\UserRequestedMods", s)
end

function ModLoaderMainmenu.UpdateMod()
	---@type CPPLMMMod?
	local mp = ModLoaderMainmenu.Scroll:GetElementOf(XGUIEng.GetCurrentWidgetID())
	if not mp then
		return
	end
	XGUIEng.SetText(XGUIEng.GetCurrentWidgetID(), "@center " .. mp.Name)
	local h = (mp == ModLoaderMainmenu.Scroll:GetSelected()) and 255 or 200
	XGUIEng.SetMaterialColor(XGUIEng.GetCurrentWidgetID(), 4, h, h, h, 255)
	XGUIEng.HighLightButton(XGUIEng.GetCurrentWidgetID(), (mp.Active or mp == ModLoaderMainmenu.Scroll:GetSelected()) and 1 or 0)
end

function ModLoaderMainmenu.ActionActive()
	---@type CPPLMMMod?
	local mp = ModLoaderMainmenu.Scroll:GetSelected()
	if not mp then
		return
	end
	mp.Active = not mp.Active
	ModLoaderMainmenu.StoreUserRequestedModpacks()
end

function ModLoaderMainmenu.UpdateActive()
	---@type CPPLMMMod?
	local mp = ModLoaderMainmenu.Scroll:GetSelected()
	if not mp then
		XGUIEng.SetText("OptionsMenuCppLogic_Settings_Desc", "")
		XGUIEng.ShowWidget("OptionsMenuCppLogic_Settings_On", 0)
		XGUIEng.ShowWidget("OptionsMenuCppLogic_Settings_IG", 0)
		XGUIEng.ShowWidget("OptionsMenuCppLogic_Settings_MM", 0)
		return
	end
	XGUIEng.SetText("OptionsMenuCppLogic_Settings_Desc", mp.Description or "")
	XGUIEng.ShowWidget("OptionsMenuCppLogic_Settings_On", 1)
	XGUIEng.HighLightButton("OptionsMenuCppLogic_Settings_On", mp.Active and 1 or 0)
	XGUIEng.ShowWidget("OptionsMenuCppLogic_Settings_IG", 1)
	XGUIEng.DisableButton("OptionsMenuCppLogic_Settings_IG", mp.UserRequestable and 0 or 1)
	XGUIEng.HighLightButton("OptionsMenuCppLogic_Settings_IG", mp.UserRequestable and 1 or 0)
	XGUIEng.ShowWidget("OptionsMenuCppLogic_Settings_MM", 1)
	XGUIEng.DisableButton("OptionsMenuCppLogic_Settings_MM", mp.MainmenuMod and 0 or 1)
	XGUIEng.HighLightButton("OptionsMenuCppLogic_Settings_MM", mp.MainmenuMod and 1 or 0)
end

function ModLoaderMainmenu.IsSavegameValid(save)
	local map, t, cn, guid, valid = CppLogic.API.SaveGetMapInfo(save, true)
	if not valid then
		return false
	end
	local mapguid, ml = ModLoader.ParseSaveGUID(guid, map, t, cn)
	if not mapguid or not ml then -- map not found | guid missmatch
		return false
	end
	local r = true
	xpcall(function()
		local modlist = ModLoader.DiscoverRequired(ml)
		ModLoader.SortMods(modlist)
	end, function(msg)
		r = false
	end)
	return r
end
CppLogic.ModLoader.OverrideSavegameValid(ModLoaderMainmenu.IsSavegameValid)

function ModLoaderMainmenu.LoadMainmenuModPacks()
	local s = {}
	for _, m in ipairs(ModLoaderMainmenu.ModPacks) do
		if m.Active then
			table.insert(s, m.Name)
		end
	end
	local ml = ModLoader.DiscoverRequired(s)
	ModLoader.SortMods(ml)
	for i = table.getn(ml.Mods), 1, -1 do
		if not ml.Mods[i].MainmenuMod then
			table.remove(ml.Mods, i)
		end
	end
	ModLoader.LoadArchives(ml)
	for _, m in ipairs(ml.Mods) do
		if m.MainmenuPath ~= "" then
			Script.Load(m.MainmenuPath)
		end
	end
	ModLoader.CleanupMods(ml, false, false, true)
end

---@diagnostic disable-next-line: duplicate-set-field
ModLoader.CheckUserRequestedMod = ModLoader.IsUserRequestedModWhitelisted

---@param map string
---@param type number
---@param cname string?
---@param userRequested string[]?
---@return ModList
function ModLoaderMainmenu.PredictMapModPacks(map, type, cname, userRequested)
	local r, i, ur = CppLogic.ModLoader.MapGetModPacks(map, type, cname)
	---@diagnostic disable-next-line: inject-field
	ModLoader.UserRequestedModWhitelisted = ur
	---@type ModList
	local modlist = {Mods = {}, Incompatible = i, Failed = {}}
	ModLoader.DiscoverRequired(r, modlist, nil, true)
	ModLoader.DiscoverUserRequested(modlist, userRequested, true)
	ModLoader.SortMods(modlist, true)
	return modlist
end

function ModLoaderMainmenu.UpdateMonitor()
	---@type CPPLMonitorInfo?
	local m = ModLoaderMainmenu.MonitorScroll:GetElementOf(XGUIEng.GetCurrentWidgetID())
	if not m then
		return
	end
	local t
	if m.Name == "" then
		t = XGUIEng.GetStringTableText("CppLogic_Mainmenu/Off")
	else
		t = string.format("%s (%d x %d)", m.Name, m.W, m.H)
	end
	XGUIEng.SetText(XGUIEng.GetCurrentWidgetID(), t)
	XGUIEng.HighLightButton(XGUIEng.GetCurrentWidgetID(), m.Name == GDB.GetString("CppLogic\\BordelessFullscreenOn") and 1 or 0)
end

function ModLoaderMainmenu.ActionMonitor()
	---@type CPPLMonitorInfo?
	local m = ModLoaderMainmenu.MonitorScroll:GetElementOf(XGUIEng.GetCurrentWidgetID())
	if not m then
		return
	end
	GDB.SetString("CppLogic\\BordelessFullscreenOn", m.Name)
end

function ModLoaderMainmenu.UpdateMonitorSelect()
	if not ModLoaderMainmenu.MonitorScroll.Over[1] then
		local on = GDB.GetString("CppLogic\\BordelessFullscreenOn") ~= ""
		XGUIEng.HighLightButton(XGUIEng.GetCurrentWidgetID(), on and 1 or 0)
		XGUIEng.ShowWidget("OptionsMenu30_ResExtraList", on and 1 or 0)
		XGUIEng.ShowWidget("OptionsMenu30_ResolutionList", on and 0 or 1)

		local m = CppLogic.API.GetMonitors()
		table.insert(m, 1, {
			Name = "",
			H = 0,
			W = 0,
		})
		ModLoaderMainmenu.MonitorScroll:SetDataToScrollOver(m)
	end
end

function ModLoaderMainmenu.ActionMonitorSelect()
	local on = XGUIEng.IsButtonHighLighted(XGUIEng.GetCurrentWidgetID()) == 0
	XGUIEng.HighLightButton(XGUIEng.GetCurrentWidgetID(), on and 1 or 0)
	XGUIEng.ShowWidget("OptionsMenu30_ResExtraList", on and 1 or 0)
	XGUIEng.ShowWidget("OptionsMenu30_ResolutionList", on and 0 or 1)
end

function ModLoaderMainmenu.InitUI()
	if not CppLogic.UI.TextButtonSetCenterText then
		function CppLogic.UI.TextButtonSetCenterText()
		end
	end
	assert(XGUIEng.GetWidgetID("OptionsMenu10_ToCppLogic") == 0, "OptionsMenu10_ToCppLogic already exists")
	CppLogic.UI.ContainerWidgetCreateTextButtonWidgetChild("OptionsMenu10", "OptionsMenu10_ToCppLogic", "OptionsMenu10_RightBG")
	CppLogic.UI.WidgetSetPositionAndSize("OptionsMenu10_ToCppLogic", 709, 420, 278, 47)
	XGUIEng.ShowWidget("OptionsMenu10_ToCppLogic", 1)
	CppLogic.UI.WidgetSetBaseData("OptionsMenu10_ToCppLogic", 5, false, false)
	CppLogic.UI.WidgetSetGroup("OptionsMenu10_ToCppLogic", "OptionGroup")
	XGUIEng.DisableButton("OptionsMenu10_ToCppLogic", 0)
	XGUIEng.HighLightButton("OptionsMenu10_ToCppLogic", 0)
	CppLogic.UI.ButtonOverrideActionFunc("OptionsMenu10_ToCppLogic", function()
		ModLoaderMainmenu.Show()
	end)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenu10_ToCppLogic", 0, 0, 0, 1, 1)
	XGUIEng.SetMaterialTexture("OptionsMenu10_ToCppLogic", 0, "data\\graphics\\textures\\gui\\mainmenu\\right_button.png")
	XGUIEng.SetMaterialColor("OptionsMenu10_ToCppLogic", 0, 255, 255, 255, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenu10_ToCppLogic", 1, 0, 0, 1, 1)
	XGUIEng.SetMaterialTexture("OptionsMenu10_ToCppLogic", 1, "data\\graphics\\textures\\gui\\mainmenu\\right_button_hi.png")
	XGUIEng.SetMaterialColor("OptionsMenu10_ToCppLogic", 1, 255, 255, 255, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenu10_ToCppLogic", 2, 0, 0, 1, 1)
	XGUIEng.SetMaterialTexture("OptionsMenu10_ToCppLogic", 2, "data\\graphics\\textures\\gui\\mainmenu\\right_button_sel.png")
	XGUIEng.SetMaterialColor("OptionsMenu10_ToCppLogic", 2, 255, 255, 255, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenu10_ToCppLogic", 3, 0, 0, 1, 1)
	XGUIEng.SetMaterialTexture("OptionsMenu10_ToCppLogic", 3, "data\\graphics\\textures\\gui\\mainmenu\\right_button_in.png")
	XGUIEng.SetMaterialColor("OptionsMenu10_ToCppLogic", 3, 254, 254, 254, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenu10_ToCppLogic", 4, 0, 0, 1, 1)
	XGUIEng.SetMaterialTexture("OptionsMenu10_ToCppLogic", 4, "data\\graphics\\textures\\gui\\mainmenu\\right_button_akt.png")
	XGUIEng.SetMaterialColor("OptionsMenu10_ToCppLogic", 4, 255, 255, 255, 255)
	CppLogic.UI.WidgetSetTooltipData("OptionsMenu10_ToCppLogic", "StartMenu_TooltipText", true, true)
	CppLogic.UI.WidgetSetTooltipString("OptionsMenu10_ToCppLogic", "CppLogic_Mainmenu/ModPacksTT", true)
	CppLogic.UI.WidgetSetUpdateManualFlag("OptionsMenu10_ToCppLogic", true)
	CppLogic.UI.WidgetSetFont("OptionsMenu10_ToCppLogic", "data\\menu\\fonts\\mainmenularge.met")
	CppLogic.UI.WidgetSetStringFrameDistance("OptionsMenu10_ToCppLogic", 3)
	XGUIEng.SetTextKeyName("OptionsMenu10_ToCppLogic", "CppLogic_Mainmenu/ModPacksBTN")
	XGUIEng.SetTextColor("OptionsMenu10_ToCppLogic", 255, 255, 255, 255)
	CppLogic.UI.TextButtonSetCenterText("OptionsMenu10_ToCppLogic", true)

	if not CppLogic.UI.TextButtonSetCenterText then
		function CppLogic.UI.TextButtonSetCenterText()
		end
	end
	assert(XGUIEng.GetWidgetID("OptionsMenu20_ToCppLogic") == 0, "OptionsMenu20_ToCppLogic already exists")
	CppLogic.UI.ContainerWidgetCreateTextButtonWidgetChild("OptionsMenu20", "OptionsMenu20_ToCppLogic", "OptionsMenu20_RightBG")
	CppLogic.UI.WidgetSetPositionAndSize("OptionsMenu20_ToCppLogic", 709, 420, 278, 47)
	XGUIEng.ShowWidget("OptionsMenu20_ToCppLogic", 1)
	CppLogic.UI.WidgetSetBaseData("OptionsMenu20_ToCppLogic", 5, false, false)
	CppLogic.UI.WidgetSetGroup("OptionsMenu20_ToCppLogic", "OptionGroup")
	XGUIEng.DisableButton("OptionsMenu20_ToCppLogic", 0)
	XGUIEng.HighLightButton("OptionsMenu20_ToCppLogic", 0)
	CppLogic.UI.ButtonOverrideActionFunc("OptionsMenu20_ToCppLogic", function()
		ModLoaderMainmenu.Show()
	end)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenu20_ToCppLogic", 0, 0, 0, 1, 1)
	XGUIEng.SetMaterialTexture("OptionsMenu20_ToCppLogic", 0, "data\\graphics\\textures\\gui\\mainmenu\\right_button.png")
	XGUIEng.SetMaterialColor("OptionsMenu20_ToCppLogic", 0, 255, 255, 255, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenu20_ToCppLogic", 1, 0, 0, 1, 1)
	XGUIEng.SetMaterialTexture("OptionsMenu20_ToCppLogic", 1, "data\\graphics\\textures\\gui\\mainmenu\\right_button_hi.png")
	XGUIEng.SetMaterialColor("OptionsMenu20_ToCppLogic", 1, 255, 255, 255, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenu20_ToCppLogic", 2, 0, 0, 1, 1)
	XGUIEng.SetMaterialTexture("OptionsMenu20_ToCppLogic", 2, "data\\graphics\\textures\\gui\\mainmenu\\right_button_sel.png")
	XGUIEng.SetMaterialColor("OptionsMenu20_ToCppLogic", 2, 255, 255, 255, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenu20_ToCppLogic", 3, 0, 0, 1, 1)
	XGUIEng.SetMaterialTexture("OptionsMenu20_ToCppLogic", 3, "data\\graphics\\textures\\gui\\mainmenu\\right_button_in.png")
	XGUIEng.SetMaterialColor("OptionsMenu20_ToCppLogic", 3, 254, 254, 254, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenu20_ToCppLogic", 4, 0, 0, 1, 1)
	XGUIEng.SetMaterialTexture("OptionsMenu20_ToCppLogic", 4, "data\\graphics\\textures\\gui\\mainmenu\\right_button_akt.png")
	XGUIEng.SetMaterialColor("OptionsMenu20_ToCppLogic", 4, 255, 255, 255, 255)
	CppLogic.UI.WidgetSetTooltipData("OptionsMenu20_ToCppLogic", "StartMenu_TooltipText", true, true)
	CppLogic.UI.WidgetSetTooltipString("OptionsMenu20_ToCppLogic", "CppLogic_Mainmenu/ModPacksTT", true)
	CppLogic.UI.WidgetSetUpdateManualFlag("OptionsMenu20_ToCppLogic", true)
	CppLogic.UI.WidgetSetFont("OptionsMenu20_ToCppLogic", "data\\menu\\fonts\\mainmenularge.met")
	CppLogic.UI.WidgetSetStringFrameDistance("OptionsMenu20_ToCppLogic", 3)
	XGUIEng.SetTextKeyName("OptionsMenu20_ToCppLogic", "CppLogic_Mainmenu/ModPacksBTN")
	XGUIEng.SetTextColor("OptionsMenu20_ToCppLogic", 255, 255, 255, 255)
	CppLogic.UI.TextButtonSetCenterText("OptionsMenu20_ToCppLogic", true)

	if not CppLogic.UI.TextButtonSetCenterText then
		function CppLogic.UI.TextButtonSetCenterText()
		end
	end
	assert(XGUIEng.GetWidgetID("OptionsMenu30_ToCppLogic") == 0, "OptionsMenu30_ToCppLogic already exists")
	CppLogic.UI.ContainerWidgetCreateTextButtonWidgetChild("OptionsMenu30", "OptionsMenu30_ToCppLogic", "OptionsMenu30_RightBG")
	CppLogic.UI.WidgetSetPositionAndSize("OptionsMenu30_ToCppLogic", 709, 420, 278, 47)
	XGUIEng.ShowWidget("OptionsMenu30_ToCppLogic", 1)
	CppLogic.UI.WidgetSetBaseData("OptionsMenu30_ToCppLogic", 5, false, false)
	CppLogic.UI.WidgetSetGroup("OptionsMenu30_ToCppLogic", "OptionGroup")
	XGUIEng.DisableButton("OptionsMenu30_ToCppLogic", 0)
	XGUIEng.HighLightButton("OptionsMenu30_ToCppLogic", 0)
	CppLogic.UI.ButtonOverrideActionFunc("OptionsMenu30_ToCppLogic", function()
		ModLoaderMainmenu.Show()
	end)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenu30_ToCppLogic", 0, 0, 0, 1, 1)
	XGUIEng.SetMaterialTexture("OptionsMenu30_ToCppLogic", 0, "data\\graphics\\textures\\gui\\mainmenu\\right_button.png")
	XGUIEng.SetMaterialColor("OptionsMenu30_ToCppLogic", 0, 255, 255, 255, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenu30_ToCppLogic", 1, 0, 0, 1, 1)
	XGUIEng.SetMaterialTexture("OptionsMenu30_ToCppLogic", 1, "data\\graphics\\textures\\gui\\mainmenu\\right_button_hi.png")
	XGUIEng.SetMaterialColor("OptionsMenu30_ToCppLogic", 1, 255, 255, 255, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenu30_ToCppLogic", 2, 0, 0, 1, 1)
	XGUIEng.SetMaterialTexture("OptionsMenu30_ToCppLogic", 2, "data\\graphics\\textures\\gui\\mainmenu\\right_button_sel.png")
	XGUIEng.SetMaterialColor("OptionsMenu30_ToCppLogic", 2, 255, 255, 255, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenu30_ToCppLogic", 3, 0, 0, 1, 1)
	XGUIEng.SetMaterialTexture("OptionsMenu30_ToCppLogic", 3, "data\\graphics\\textures\\gui\\mainmenu\\right_button_in.png")
	XGUIEng.SetMaterialColor("OptionsMenu30_ToCppLogic", 3, 254, 254, 254, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenu30_ToCppLogic", 4, 0, 0, 1, 1)
	XGUIEng.SetMaterialTexture("OptionsMenu30_ToCppLogic", 4, "data\\graphics\\textures\\gui\\mainmenu\\right_button_akt.png")
	XGUIEng.SetMaterialColor("OptionsMenu30_ToCppLogic", 4, 255, 255, 255, 255)
	CppLogic.UI.WidgetSetTooltipData("OptionsMenu30_ToCppLogic", "StartMenu_TooltipText", true, true)
	CppLogic.UI.WidgetSetTooltipString("OptionsMenu30_ToCppLogic", "CppLogic_Mainmenu/ModPacksTT", true)
	CppLogic.UI.WidgetSetUpdateManualFlag("OptionsMenu30_ToCppLogic", true)
	CppLogic.UI.WidgetSetFont("OptionsMenu30_ToCppLogic", "data\\menu\\fonts\\mainmenularge.met")
	CppLogic.UI.WidgetSetStringFrameDistance("OptionsMenu30_ToCppLogic", 3)
	XGUIEng.SetTextKeyName("OptionsMenu30_ToCppLogic", "CppLogic_Mainmenu/ModPacksBTN")
	XGUIEng.SetTextColor("OptionsMenu30_ToCppLogic", 255, 255, 255, 255)
	CppLogic.UI.TextButtonSetCenterText("OptionsMenu30_ToCppLogic", true)

	if not CppLogic.UI.TextButtonSetCenterText then
		function CppLogic.UI.TextButtonSetCenterText()
		end
	end
	assert(XGUIEng.GetWidgetID("OptionsMenu40_ToCppLogic") == 0, "OptionsMenu40_ToCppLogic already exists")
	CppLogic.UI.ContainerWidgetCreateTextButtonWidgetChild("OptionsMenu40", "OptionsMenu40_ToCppLogic", "OptionsMenu40_RightBG")
	CppLogic.UI.WidgetSetPositionAndSize("OptionsMenu40_ToCppLogic", 709, 420, 278, 47)
	XGUIEng.ShowWidget("OptionsMenu40_ToCppLogic", 1)
	CppLogic.UI.WidgetSetBaseData("OptionsMenu40_ToCppLogic", 5, false, false)
	CppLogic.UI.WidgetSetGroup("OptionsMenu40_ToCppLogic", "OptionGroup")
	XGUIEng.DisableButton("OptionsMenu40_ToCppLogic", 0)
	XGUIEng.HighLightButton("OptionsMenu40_ToCppLogic", 0)
	CppLogic.UI.ButtonOverrideActionFunc("OptionsMenu40_ToCppLogic", function()
		ModLoaderMainmenu.Show()
	end)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenu40_ToCppLogic", 0, 0, 0, 1, 1)
	XGUIEng.SetMaterialTexture("OptionsMenu40_ToCppLogic", 0, "data\\graphics\\textures\\gui\\mainmenu\\right_button.png")
	XGUIEng.SetMaterialColor("OptionsMenu40_ToCppLogic", 0, 255, 255, 255, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenu40_ToCppLogic", 1, 0, 0, 1, 1)
	XGUIEng.SetMaterialTexture("OptionsMenu40_ToCppLogic", 1, "data\\graphics\\textures\\gui\\mainmenu\\right_button_hi.png")
	XGUIEng.SetMaterialColor("OptionsMenu40_ToCppLogic", 1, 255, 255, 255, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenu40_ToCppLogic", 2, 0, 0, 1, 1)
	XGUIEng.SetMaterialTexture("OptionsMenu40_ToCppLogic", 2, "data\\graphics\\textures\\gui\\mainmenu\\right_button_sel.png")
	XGUIEng.SetMaterialColor("OptionsMenu40_ToCppLogic", 2, 255, 255, 255, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenu40_ToCppLogic", 3, 0, 0, 1, 1)
	XGUIEng.SetMaterialTexture("OptionsMenu40_ToCppLogic", 3, "data\\graphics\\textures\\gui\\mainmenu\\right_button_in.png")
	XGUIEng.SetMaterialColor("OptionsMenu40_ToCppLogic", 3, 254, 254, 254, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenu40_ToCppLogic", 4, 0, 0, 1, 1)
	XGUIEng.SetMaterialTexture("OptionsMenu40_ToCppLogic", 4, "data\\graphics\\textures\\gui\\mainmenu\\right_button_akt.png")
	XGUIEng.SetMaterialColor("OptionsMenu40_ToCppLogic", 4, 255, 255, 255, 255)
	CppLogic.UI.WidgetSetTooltipData("OptionsMenu40_ToCppLogic", "StartMenu_TooltipText", true, true)
	CppLogic.UI.WidgetSetTooltipString("OptionsMenu40_ToCppLogic", "CppLogic_Mainmenu/ModPacksTT", true)
	CppLogic.UI.WidgetSetUpdateManualFlag("OptionsMenu40_ToCppLogic", true)
	CppLogic.UI.WidgetSetFont("OptionsMenu40_ToCppLogic", "data\\menu\\fonts\\mainmenularge.met")
	CppLogic.UI.WidgetSetStringFrameDistance("OptionsMenu40_ToCppLogic", 3)
	XGUIEng.SetTextKeyName("OptionsMenu40_ToCppLogic", "CppLogic_Mainmenu/ModPacksBTN")
	XGUIEng.SetTextColor("OptionsMenu40_ToCppLogic", 255, 255, 255, 255)
	CppLogic.UI.TextButtonSetCenterText("OptionsMenu40_ToCppLogic", true)

	if not CppLogic.UI.TextButtonSetCenterText then
		function CppLogic.UI.TextButtonSetCenterText()
		end
	end
	assert(XGUIEng.GetWidgetID("OptionsMenu50_ToCppLogic") == 0, "OptionsMenu50_ToCppLogic already exists")
	CppLogic.UI.ContainerWidgetCreateTextButtonWidgetChild("OptionsMenu50", "OptionsMenu50_ToCppLogic", "OptionsMenu50_Connection_Modem")
	CppLogic.UI.WidgetSetPositionAndSize("OptionsMenu50_ToCppLogic", 709, 420, 278, 47)
	XGUIEng.ShowWidget("OptionsMenu50_ToCppLogic", 1)
	CppLogic.UI.WidgetSetBaseData("OptionsMenu50_ToCppLogic", 5, false, false)
	CppLogic.UI.WidgetSetGroup("OptionsMenu50_ToCppLogic", "OptionGroup")
	XGUIEng.DisableButton("OptionsMenu50_ToCppLogic", 0)
	XGUIEng.HighLightButton("OptionsMenu50_ToCppLogic", 0)
	CppLogic.UI.ButtonOverrideActionFunc("OptionsMenu50_ToCppLogic", function()
		ModLoaderMainmenu.Show()
	end)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenu50_ToCppLogic", 0, 0, 0, 1, 1)
	XGUIEng.SetMaterialTexture("OptionsMenu50_ToCppLogic", 0, "data\\graphics\\textures\\gui\\mainmenu\\right_button.png")
	XGUIEng.SetMaterialColor("OptionsMenu50_ToCppLogic", 0, 255, 255, 255, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenu50_ToCppLogic", 1, 0, 0, 1, 1)
	XGUIEng.SetMaterialTexture("OptionsMenu50_ToCppLogic", 1, "data\\graphics\\textures\\gui\\mainmenu\\right_button_hi.png")
	XGUIEng.SetMaterialColor("OptionsMenu50_ToCppLogic", 1, 255, 255, 255, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenu50_ToCppLogic", 2, 0, 0, 1, 1)
	XGUIEng.SetMaterialTexture("OptionsMenu50_ToCppLogic", 2, "data\\graphics\\textures\\gui\\mainmenu\\right_button_sel.png")
	XGUIEng.SetMaterialColor("OptionsMenu50_ToCppLogic", 2, 255, 255, 255, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenu50_ToCppLogic", 3, 0, 0, 1, 1)
	XGUIEng.SetMaterialTexture("OptionsMenu50_ToCppLogic", 3, "data\\graphics\\textures\\gui\\mainmenu\\right_button_in.png")
	XGUIEng.SetMaterialColor("OptionsMenu50_ToCppLogic", 3, 254, 254, 254, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenu50_ToCppLogic", 4, 0, 0, 1, 1)
	XGUIEng.SetMaterialTexture("OptionsMenu50_ToCppLogic", 4, "data\\graphics\\textures\\gui\\mainmenu\\right_button_akt.png")
	XGUIEng.SetMaterialColor("OptionsMenu50_ToCppLogic", 4, 255, 255, 255, 255)
	CppLogic.UI.WidgetSetTooltipData("OptionsMenu50_ToCppLogic", "StartMenu_TooltipText", true, true)
	CppLogic.UI.WidgetSetTooltipString("OptionsMenu50_ToCppLogic", "CppLogic_Mainmenu/ModPacksTT", true)
	CppLogic.UI.WidgetSetUpdateManualFlag("OptionsMenu50_ToCppLogic", true)
	CppLogic.UI.WidgetSetFont("OptionsMenu50_ToCppLogic", "data\\menu\\fonts\\mainmenularge.met")
	CppLogic.UI.WidgetSetStringFrameDistance("OptionsMenu50_ToCppLogic", 3)
	XGUIEng.SetTextKeyName("OptionsMenu50_ToCppLogic", "CppLogic_Mainmenu/ModPacksBTN")
	XGUIEng.SetTextColor("OptionsMenu50_ToCppLogic", 255, 255, 255, 255)
	CppLogic.UI.TextButtonSetCenterText("OptionsMenu50_ToCppLogic", true)

	if not CppLogic.UI.TextButtonSetCenterText then
		function CppLogic.UI.TextButtonSetCenterText()
		end
	end
	assert(XGUIEng.GetWidgetID("OptionsMenuCppLogic") == 0, "OptionsMenuCppLogic already exists")
	assert(XGUIEng.GetWidgetID("OptionsMenuCppLogic_Back") == 0, "OptionsMenuCppLogic_Back already exists")
	assert(XGUIEng.GetWidgetID("OptionsMenuCppLogic_ToControl") == 0, "OptionsMenuCppLogic_ToControl already exists")
	assert(XGUIEng.GetWidgetID("OptionsMenuCppLogic_ToGraphics") == 0, "OptionsMenuCppLogic_ToGraphics already exists")
	assert(XGUIEng.GetWidgetID("OptionsMenuCppLogic_ToNetwork") == 0, "OptionsMenuCppLogic_ToNetwork already exists")
	assert(XGUIEng.GetWidgetID("OptionsMenuCppLogic_ToSound") == 0, "OptionsMenuCppLogic_ToSound already exists")
	assert(XGUIEng.GetWidgetID("OptionsMenuCppLogic_ToUser") == 0, "OptionsMenuCppLogic_ToUser already exists")
	assert(XGUIEng.GetWidgetID("OptionsMenuCppLogic_ToCppLogic") == 0, "OptionsMenuCppLogic_ToCppLogic already exists")
	assert(XGUIEng.GetWidgetID("OptionsMenuCppLogic_RightBG") == 0, "OptionsMenuCppLogic_RightBG already exists")
	assert(XGUIEng.GetWidgetID("OptionsMenuCppLogic_MainContainer") == 0, "OptionsMenuCppLogic_MainContainer already exists")
	assert(XGUIEng.GetWidgetID("OptionsMenuCppLogic_Headline") == 0, "OptionsMenuCppLogic_Headline already exists")
	assert(XGUIEng.GetWidgetID("OptionsMenuCppLogic_SettingsHeadline") == 0, "OptionsMenuCppLogic_SettingsHeadline already exists")
	assert(XGUIEng.GetWidgetID("OptionsMenuCppLogic_ModList") == 0, "OptionsMenuCppLogic_ModList already exists")
	assert(XGUIEng.GetWidgetID("OptionsMenuCppLogic_ModListList") == 0, "OptionsMenuCppLogic_ModListList already exists")
	assert(XGUIEng.GetWidgetID("OptionsMenuCppLogic_ModListSelect") == 0, "OptionsMenuCppLogic_ModListSelect already exists")
	assert(XGUIEng.GetWidgetID("OptionsMenuCppLogic_ModListScroll") == 0, "OptionsMenuCppLogic_ModListScroll already exists")
	assert(XGUIEng.GetWidgetID("OptionsMenuCppLogic_Settings") == 0, "OptionsMenuCppLogic_Settings already exists")
	assert(XGUIEng.GetWidgetID("OptionsMenuCppLogic_Settings_On") == 0, "OptionsMenuCppLogic_Settings_On already exists")
	assert(XGUIEng.GetWidgetID("OptionsMenuCppLogic_Settings_Desc") == 0, "OptionsMenuCppLogic_Settings_Desc already exists")
	assert(XGUIEng.GetWidgetID("OptionsMenuCppLogic_Settings_IG") == 0, "OptionsMenuCppLogic_Settings_IG already exists")
	assert(XGUIEng.GetWidgetID("OptionsMenuCppLogic_Settings_MM") == 0, "OptionsMenuCppLogic_Settings_MM already exists")
	assert(XGUIEng.GetWidgetID("OptionsMenuCppLogic_BG") == 0, "OptionsMenuCppLogic_BG already exists")
	assert(XGUIEng.GetWidgetID("OptionsMenuCppLogic_BGShade") == 0, "OptionsMenuCppLogic_BGShade already exists")
	assert(XGUIEng.GetWidgetID("OptionsMenuCppLogic_BGBottom") == 0, "OptionsMenuCppLogic_BGBottom already exists")
	assert(XGUIEng.GetWidgetID("OptionsMenuCppLogic_BGFrameLeft") == 0, "OptionsMenuCppLogic_BGFrameLeft already exists")
	assert(XGUIEng.GetWidgetID("OptionsMenuCppLogic_BGFrameRight") == 0, "OptionsMenuCppLogic_BGFrameRight already exists")
	assert(XGUIEng.GetWidgetID("OptionsMenuCppLogic_BGTop") == 0, "OptionsMenuCppLogic_BGTop already exists")
	CppLogic.UI.ContainerWidgetCreateContainerWidgetChild("Screens", "OptionsMenuCppLogic", nil)
	CppLogic.UI.WidgetSetPositionAndSize("OptionsMenuCppLogic", 0, 0, 1024, 768)
	XGUIEng.ShowWidget("OptionsMenuCppLogic", 0)
	CppLogic.UI.WidgetSetBaseData("OptionsMenuCppLogic", 0, false, false)
	CppLogic.UI.ContainerWidgetCreateTextButtonWidgetChild("OptionsMenuCppLogic", "OptionsMenuCppLogic_Back", nil)
	CppLogic.UI.WidgetSetPositionAndSize("OptionsMenuCppLogic_Back", 709, 500, 278, 47)
	XGUIEng.ShowWidget("OptionsMenuCppLogic_Back", 1)
	CppLogic.UI.WidgetSetBaseData("OptionsMenuCppLogic_Back", 5, false, false)
	XGUIEng.DisableButton("OptionsMenuCppLogic_Back", 0)
	XGUIEng.HighLightButton("OptionsMenuCppLogic_Back", 0)
	CppLogic.UI.ButtonOverrideActionFunc("OptionsMenuCppLogic_Back", function()
		OptionsMenu.S00_Button_ToStart()
	end)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenuCppLogic_Back", 0, 0, 0, 1, 1)
	XGUIEng.SetMaterialTexture("OptionsMenuCppLogic_Back", 0, "data\\graphics\\textures\\gui\\mainmenu\\right_button.png")
	XGUIEng.SetMaterialColor("OptionsMenuCppLogic_Back", 0, 255, 255, 255, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenuCppLogic_Back", 1, 0, 0, 1, 1)
	XGUIEng.SetMaterialTexture("OptionsMenuCppLogic_Back", 1, "data\\graphics\\textures\\gui\\mainmenu\\right_button_hi.png")
	XGUIEng.SetMaterialColor("OptionsMenuCppLogic_Back", 1, 255, 255, 255, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenuCppLogic_Back", 2, 0, 0, 1, 1)
	XGUIEng.SetMaterialTexture("OptionsMenuCppLogic_Back", 2, "data\\graphics\\textures\\gui\\mainmenu\\right_button_sel.png")
	XGUIEng.SetMaterialColor("OptionsMenuCppLogic_Back", 2, 255, 255, 255, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenuCppLogic_Back", 3, 0, 0, 1, 1)
	XGUIEng.SetMaterialTexture("OptionsMenuCppLogic_Back", 3, "data\\graphics\\textures\\gui\\mainmenu\\right_button_in.png")
	XGUIEng.SetMaterialColor("OptionsMenuCppLogic_Back", 3, 254, 254, 254, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenuCppLogic_Back", 4, 0, 0, 1, 1)
	XGUIEng.SetMaterialTexture("OptionsMenuCppLogic_Back", 4, "data\\graphics\\textures\\gui\\mainmenu\\right_button_akt.png")
	XGUIEng.SetMaterialColor("OptionsMenuCppLogic_Back", 4, 255, 255, 255, 255)
	CppLogic.UI.WidgetSetTooltipData("OptionsMenuCppLogic_Back", "StartMenu_TooltipText", true, true)
	CppLogic.UI.WidgetSetTooltipString("OptionsMenuCppLogic_Back", "MainMenuTooltips/OptionsMenu00_Back", true)
	CppLogic.UI.WidgetSetUpdateManualFlag("OptionsMenuCppLogic_Back", true)
	CppLogic.UI.WidgetSetFont("OptionsMenuCppLogic_Back", "data\\menu\\fonts\\mainmenularge.met")
	CppLogic.UI.WidgetSetStringFrameDistance("OptionsMenuCppLogic_Back", 3)
	XGUIEng.SetTextKeyName("OptionsMenuCppLogic_Back", "MainMenu/Back")
	XGUIEng.SetTextColor("OptionsMenuCppLogic_Back", 255, 255, 255, 255)
	CppLogic.UI.TextButtonSetCenterText("OptionsMenuCppLogic_Back", true)
	CppLogic.UI.ContainerWidgetCreateTextButtonWidgetChild("OptionsMenuCppLogic", "OptionsMenuCppLogic_ToControl", nil)
	CppLogic.UI.WidgetSetPositionAndSize("OptionsMenuCppLogic_ToControl", 709, 220, 278, 47)
	XGUIEng.ShowWidget("OptionsMenuCppLogic_ToControl", 1)
	CppLogic.UI.WidgetSetBaseData("OptionsMenuCppLogic_ToControl", 5, false, false)
	CppLogic.UI.WidgetSetGroup("OptionsMenuCppLogic_ToControl", "OptionGroup")
	XGUIEng.DisableButton("OptionsMenuCppLogic_ToControl", 0)
	XGUIEng.HighLightButton("OptionsMenuCppLogic_ToControl", 0)
	CppLogic.UI.ButtonOverrideActionFunc("OptionsMenuCppLogic_ToControl", function()
		OptionsMenu.S20_Start()
	end)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenuCppLogic_ToControl", 0, 0, 0, 1, 1)
	XGUIEng.SetMaterialTexture("OptionsMenuCppLogic_ToControl", 0, "data\\graphics\\textures\\gui\\mainmenu\\right_button.png")
	XGUIEng.SetMaterialColor("OptionsMenuCppLogic_ToControl", 0, 255, 255, 255, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenuCppLogic_ToControl", 1, 0, 0, 1, 1)
	XGUIEng.SetMaterialTexture("OptionsMenuCppLogic_ToControl", 1, "data\\graphics\\textures\\gui\\mainmenu\\right_button_hi.png")
	XGUIEng.SetMaterialColor("OptionsMenuCppLogic_ToControl", 1, 255, 255, 255, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenuCppLogic_ToControl", 2, 0, 0, 1, 1)
	XGUIEng.SetMaterialTexture("OptionsMenuCppLogic_ToControl", 2, "data\\graphics\\textures\\gui\\mainmenu\\right_button_sel.png")
	XGUIEng.SetMaterialColor("OptionsMenuCppLogic_ToControl", 2, 255, 255, 255, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenuCppLogic_ToControl", 3, 0, 0, 1, 1)
	XGUIEng.SetMaterialTexture("OptionsMenuCppLogic_ToControl", 3, "data\\graphics\\textures\\gui\\mainmenu\\right_button_in.png")
	XGUIEng.SetMaterialColor("OptionsMenuCppLogic_ToControl", 3, 254, 254, 254, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenuCppLogic_ToControl", 4, 0, 0, 1, 1)
	XGUIEng.SetMaterialTexture("OptionsMenuCppLogic_ToControl", 4, "data\\graphics\\textures\\gui\\mainmenu\\right_button_akt.png")
	XGUIEng.SetMaterialColor("OptionsMenuCppLogic_ToControl", 4, 255, 255, 255, 255)
	CppLogic.UI.WidgetSetTooltipData("OptionsMenuCppLogic_ToControl", "StartMenu_TooltipText", true, true)
	CppLogic.UI.WidgetSetTooltipString("OptionsMenuCppLogic_ToControl", "MainMenuTooltips/OptionsMenu00_ToControl", true)
	CppLogic.UI.WidgetSetUpdateManualFlag("OptionsMenuCppLogic_ToControl", true)
	CppLogic.UI.WidgetSetFont("OptionsMenuCppLogic_ToControl", "data\\menu\\fonts\\mainmenularge.met")
	CppLogic.UI.WidgetSetStringFrameDistance("OptionsMenuCppLogic_ToControl", 3)
	XGUIEng.SetTextKeyName("OptionsMenuCppLogic_ToControl", "MainMenu/Options_Controls")
	XGUIEng.SetTextColor("OptionsMenuCppLogic_ToControl", 255, 255, 255, 255)
	CppLogic.UI.TextButtonSetCenterText("OptionsMenuCppLogic_ToControl", true)
	CppLogic.UI.ContainerWidgetCreateTextButtonWidgetChild("OptionsMenuCppLogic", "OptionsMenuCppLogic_ToGraphics", nil)
	CppLogic.UI.WidgetSetPositionAndSize("OptionsMenuCppLogic_ToGraphics", 709, 270, 278, 47)
	XGUIEng.ShowWidget("OptionsMenuCppLogic_ToGraphics", 1)
	CppLogic.UI.WidgetSetBaseData("OptionsMenuCppLogic_ToGraphics", 5, false, false)
	CppLogic.UI.WidgetSetGroup("OptionsMenuCppLogic_ToGraphics", "OptionGroup")
	XGUIEng.DisableButton("OptionsMenuCppLogic_ToGraphics", 0)
	XGUIEng.HighLightButton("OptionsMenuCppLogic_ToGraphics", 0)
	CppLogic.UI.ButtonOverrideActionFunc("OptionsMenuCppLogic_ToGraphics", function()
		OptionsMenu.S30_Start()
	end)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenuCppLogic_ToGraphics", 0, 0, 0, 1, 1)
	XGUIEng.SetMaterialTexture("OptionsMenuCppLogic_ToGraphics", 0, "data\\graphics\\textures\\gui\\mainmenu\\right_button.png")
	XGUIEng.SetMaterialColor("OptionsMenuCppLogic_ToGraphics", 0, 255, 255, 255, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenuCppLogic_ToGraphics", 1, 0, 0, 1, 1)
	XGUIEng.SetMaterialTexture("OptionsMenuCppLogic_ToGraphics", 1, "data\\graphics\\textures\\gui\\mainmenu\\right_button_hi.png")
	XGUIEng.SetMaterialColor("OptionsMenuCppLogic_ToGraphics", 1, 255, 255, 255, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenuCppLogic_ToGraphics", 2, 0, 0, 1, 1)
	XGUIEng.SetMaterialTexture("OptionsMenuCppLogic_ToGraphics", 2, "data\\graphics\\textures\\gui\\mainmenu\\right_button_sel.png")
	XGUIEng.SetMaterialColor("OptionsMenuCppLogic_ToGraphics", 2, 255, 255, 255, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenuCppLogic_ToGraphics", 3, 0, 0, 1, 1)
	XGUIEng.SetMaterialTexture("OptionsMenuCppLogic_ToGraphics", 3, "data\\graphics\\textures\\gui\\mainmenu\\right_button_in.png")
	XGUIEng.SetMaterialColor("OptionsMenuCppLogic_ToGraphics", 3, 254, 254, 254, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenuCppLogic_ToGraphics", 4, 0, 0, 1, 1)
	XGUIEng.SetMaterialTexture("OptionsMenuCppLogic_ToGraphics", 4, "data\\graphics\\textures\\gui\\mainmenu\\right_button_akt.png")
	XGUIEng.SetMaterialColor("OptionsMenuCppLogic_ToGraphics", 4, 255, 255, 255, 255)
	CppLogic.UI.WidgetSetTooltipData("OptionsMenuCppLogic_ToGraphics", "StartMenu_TooltipText", true, true)
	CppLogic.UI.WidgetSetTooltipString("OptionsMenuCppLogic_ToGraphics", "MainMenuTooltips/OptionsMenu00_ToGraphics", true)
	CppLogic.UI.WidgetSetUpdateManualFlag("OptionsMenuCppLogic_ToGraphics", true)
	CppLogic.UI.WidgetSetFont("OptionsMenuCppLogic_ToGraphics", "data\\menu\\fonts\\mainmenularge.met")
	CppLogic.UI.WidgetSetStringFrameDistance("OptionsMenuCppLogic_ToGraphics", 3)
	XGUIEng.SetTextKeyName("OptionsMenuCppLogic_ToGraphics", "MainMenu/Options_Graphics")
	XGUIEng.SetTextColor("OptionsMenuCppLogic_ToGraphics", 255, 255, 255, 255)
	CppLogic.UI.TextButtonSetCenterText("OptionsMenuCppLogic_ToGraphics", true)
	CppLogic.UI.ContainerWidgetCreateTextButtonWidgetChild("OptionsMenuCppLogic", "OptionsMenuCppLogic_ToNetwork", nil)
	CppLogic.UI.WidgetSetPositionAndSize("OptionsMenuCppLogic_ToNetwork", 709, 370, 278, 47)
	XGUIEng.ShowWidget("OptionsMenuCppLogic_ToNetwork", 1)
	CppLogic.UI.WidgetSetBaseData("OptionsMenuCppLogic_ToNetwork", 5, false, false)
	CppLogic.UI.WidgetSetGroup("OptionsMenuCppLogic_ToNetwork", "OptionGroup")
	XGUIEng.DisableButton("OptionsMenuCppLogic_ToNetwork", 0)
	XGUIEng.HighLightButton("OptionsMenuCppLogic_ToNetwork", 0)
	CppLogic.UI.ButtonOverrideActionFunc("OptionsMenuCppLogic_ToNetwork", function()
		OptionsMenu.S50_Start()
	end)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenuCppLogic_ToNetwork", 0, 0, 0, 1, 1)
	XGUIEng.SetMaterialTexture("OptionsMenuCppLogic_ToNetwork", 0, "data\\graphics\\textures\\gui\\mainmenu\\right_button.png")
	XGUIEng.SetMaterialColor("OptionsMenuCppLogic_ToNetwork", 0, 255, 255, 255, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenuCppLogic_ToNetwork", 1, 0, 0, 1, 1)
	XGUIEng.SetMaterialTexture("OptionsMenuCppLogic_ToNetwork", 1, "data\\graphics\\textures\\gui\\mainmenu\\right_button_hi.png")
	XGUIEng.SetMaterialColor("OptionsMenuCppLogic_ToNetwork", 1, 255, 255, 255, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenuCppLogic_ToNetwork", 2, 0, 0, 1, 1)
	XGUIEng.SetMaterialTexture("OptionsMenuCppLogic_ToNetwork", 2, "data\\graphics\\textures\\gui\\mainmenu\\right_button_sel.png")
	XGUIEng.SetMaterialColor("OptionsMenuCppLogic_ToNetwork", 2, 255, 255, 255, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenuCppLogic_ToNetwork", 3, 0, 0, 1, 1)
	XGUIEng.SetMaterialTexture("OptionsMenuCppLogic_ToNetwork", 3, "data\\graphics\\textures\\gui\\mainmenu\\right_button_in.png")
	XGUIEng.SetMaterialColor("OptionsMenuCppLogic_ToNetwork", 3, 254, 254, 254, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenuCppLogic_ToNetwork", 4, 0, 0, 1, 1)
	XGUIEng.SetMaterialTexture("OptionsMenuCppLogic_ToNetwork", 4, "data\\graphics\\textures\\gui\\mainmenu\\right_button_akt.png")
	XGUIEng.SetMaterialColor("OptionsMenuCppLogic_ToNetwork", 4, 255, 255, 255, 255)
	CppLogic.UI.WidgetSetTooltipData("OptionsMenuCppLogic_ToNetwork", "StartMenu_TooltipText", true, true)
	CppLogic.UI.WidgetSetTooltipString("OptionsMenuCppLogic_ToNetwork", "MainMenuTooltips/OptionsMenu00_ToNetwork", true)
	CppLogic.UI.WidgetSetUpdateManualFlag("OptionsMenuCppLogic_ToNetwork", true)
	CppLogic.UI.WidgetSetFont("OptionsMenuCppLogic_ToNetwork", "data\\menu\\fonts\\mainmenularge.met")
	CppLogic.UI.WidgetSetStringFrameDistance("OptionsMenuCppLogic_ToNetwork", 3)
	XGUIEng.SetTextKeyName("OptionsMenuCppLogic_ToNetwork", "MainMenu/Options_Network")
	XGUIEng.SetTextColor("OptionsMenuCppLogic_ToNetwork", 255, 255, 255, 255)
	CppLogic.UI.TextButtonSetCenterText("OptionsMenuCppLogic_ToNetwork", true)
	CppLogic.UI.ContainerWidgetCreateTextButtonWidgetChild("OptionsMenuCppLogic", "OptionsMenuCppLogic_ToSound", nil)
	CppLogic.UI.WidgetSetPositionAndSize("OptionsMenuCppLogic_ToSound", 709, 320, 278, 47)
	XGUIEng.ShowWidget("OptionsMenuCppLogic_ToSound", 1)
	CppLogic.UI.WidgetSetBaseData("OptionsMenuCppLogic_ToSound", 5, false, false)
	CppLogic.UI.WidgetSetGroup("OptionsMenuCppLogic_ToSound", "OptionGroup")
	XGUIEng.DisableButton("OptionsMenuCppLogic_ToSound", 0)
	XGUIEng.HighLightButton("OptionsMenuCppLogic_ToSound", 0)
	CppLogic.UI.ButtonOverrideActionFunc("OptionsMenuCppLogic_ToSound", function()
		OptionsMenu.S40_Start()
	end)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenuCppLogic_ToSound", 0, 0, 0, 1, 1)
	XGUIEng.SetMaterialTexture("OptionsMenuCppLogic_ToSound", 0, "data\\graphics\\textures\\gui\\mainmenu\\right_button.png")
	XGUIEng.SetMaterialColor("OptionsMenuCppLogic_ToSound", 0, 255, 255, 255, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenuCppLogic_ToSound", 1, 0, 0, 1, 1)
	XGUIEng.SetMaterialTexture("OptionsMenuCppLogic_ToSound", 1, "data\\graphics\\textures\\gui\\mainmenu\\right_button_hi.png")
	XGUIEng.SetMaterialColor("OptionsMenuCppLogic_ToSound", 1, 255, 255, 255, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenuCppLogic_ToSound", 2, 0, 0, 1, 1)
	XGUIEng.SetMaterialTexture("OptionsMenuCppLogic_ToSound", 2, "data\\graphics\\textures\\gui\\mainmenu\\right_button_sel.png")
	XGUIEng.SetMaterialColor("OptionsMenuCppLogic_ToSound", 2, 255, 255, 255, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenuCppLogic_ToSound", 3, 0, 0, 1, 1)
	XGUIEng.SetMaterialTexture("OptionsMenuCppLogic_ToSound", 3, "data\\graphics\\textures\\gui\\mainmenu\\right_button_in.png")
	XGUIEng.SetMaterialColor("OptionsMenuCppLogic_ToSound", 3, 254, 254, 254, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenuCppLogic_ToSound", 4, 0, 0, 1, 1)
	XGUIEng.SetMaterialTexture("OptionsMenuCppLogic_ToSound", 4, "data\\graphics\\textures\\gui\\mainmenu\\right_button_akt.png")
	XGUIEng.SetMaterialColor("OptionsMenuCppLogic_ToSound", 4, 255, 255, 255, 255)
	CppLogic.UI.WidgetSetTooltipData("OptionsMenuCppLogic_ToSound", "StartMenu_TooltipText", true, true)
	CppLogic.UI.WidgetSetTooltipString("OptionsMenuCppLogic_ToSound", "MainMenuTooltips/OptionsMenu00_ToSound", true)
	CppLogic.UI.WidgetSetUpdateManualFlag("OptionsMenuCppLogic_ToSound", true)
	CppLogic.UI.WidgetSetFont("OptionsMenuCppLogic_ToSound", "data\\menu\\fonts\\mainmenularge.met")
	CppLogic.UI.WidgetSetStringFrameDistance("OptionsMenuCppLogic_ToSound", 3)
	XGUIEng.SetTextKeyName("OptionsMenuCppLogic_ToSound", "MainMenu/Options_Sound")
	XGUIEng.SetTextColor("OptionsMenuCppLogic_ToSound", 255, 255, 255, 255)
	CppLogic.UI.TextButtonSetCenterText("OptionsMenuCppLogic_ToSound", true)
	CppLogic.UI.ContainerWidgetCreateTextButtonWidgetChild("OptionsMenuCppLogic", "OptionsMenuCppLogic_ToUser", nil)
	CppLogic.UI.WidgetSetPositionAndSize("OptionsMenuCppLogic_ToUser", 709, 170, 278, 47)
	XGUIEng.ShowWidget("OptionsMenuCppLogic_ToUser", 1)
	CppLogic.UI.WidgetSetBaseData("OptionsMenuCppLogic_ToUser", 5, false, false)
	CppLogic.UI.WidgetSetGroup("OptionsMenuCppLogic_ToUser", "OptionGroup")
	XGUIEng.DisableButton("OptionsMenuCppLogic_ToUser", 0)
	XGUIEng.HighLightButton("OptionsMenuCppLogic_ToUser", 0)
	CppLogic.UI.ButtonOverrideActionFunc("OptionsMenuCppLogic_ToUser", function()
		OptionsMenu.S10_Start()
	end)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenuCppLogic_ToUser", 0, 0, 0, 1, 1)
	XGUIEng.SetMaterialTexture("OptionsMenuCppLogic_ToUser", 0, "data\\graphics\\textures\\gui\\mainmenu\\right_button.png")
	XGUIEng.SetMaterialColor("OptionsMenuCppLogic_ToUser", 0, 255, 255, 255, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenuCppLogic_ToUser", 1, 0, 0, 1, 1)
	XGUIEng.SetMaterialTexture("OptionsMenuCppLogic_ToUser", 1, "data\\graphics\\textures\\gui\\mainmenu\\right_button_hi.png")
	XGUIEng.SetMaterialColor("OptionsMenuCppLogic_ToUser", 1, 255, 255, 255, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenuCppLogic_ToUser", 2, 0, 0, 1, 1)
	XGUIEng.SetMaterialTexture("OptionsMenuCppLogic_ToUser", 2, "data\\graphics\\textures\\gui\\mainmenu\\right_button_sel.png")
	XGUIEng.SetMaterialColor("OptionsMenuCppLogic_ToUser", 2, 255, 255, 255, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenuCppLogic_ToUser", 3, 0, 0, 1, 1)
	XGUIEng.SetMaterialTexture("OptionsMenuCppLogic_ToUser", 3, "data\\graphics\\textures\\gui\\mainmenu\\right_button_in.png")
	XGUIEng.SetMaterialColor("OptionsMenuCppLogic_ToUser", 3, 254, 254, 254, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenuCppLogic_ToUser", 4, 0, 0, 1, 1)
	XGUIEng.SetMaterialTexture("OptionsMenuCppLogic_ToUser", 4, "data\\graphics\\textures\\gui\\mainmenu\\right_button_akt.png")
	XGUIEng.SetMaterialColor("OptionsMenuCppLogic_ToUser", 4, 255, 255, 255, 255)
	CppLogic.UI.WidgetSetTooltipData("OptionsMenuCppLogic_ToUser", "StartMenu_TooltipText", true, true)
	CppLogic.UI.WidgetSetTooltipString("OptionsMenuCppLogic_ToUser", "MainMenuTooltips/OptionsMenu00_ToUser", true)
	CppLogic.UI.WidgetSetUpdateManualFlag("OptionsMenuCppLogic_ToUser", true)
	CppLogic.UI.WidgetSetFont("OptionsMenuCppLogic_ToUser", "data\\menu\\fonts\\mainmenularge.met")
	CppLogic.UI.WidgetSetStringFrameDistance("OptionsMenuCppLogic_ToUser", 3)
	XGUIEng.SetTextKeyName("OptionsMenuCppLogic_ToUser", "MainMenu/Options_User")
	XGUIEng.SetTextColor("OptionsMenuCppLogic_ToUser", 255, 255, 255, 255)
	CppLogic.UI.TextButtonSetCenterText("OptionsMenuCppLogic_ToUser", true)
	CppLogic.UI.ContainerWidgetCreateTextButtonWidgetChild("OptionsMenuCppLogic", "OptionsMenuCppLogic_ToCppLogic", nil)
	CppLogic.UI.WidgetSetPositionAndSize("OptionsMenuCppLogic_ToCppLogic", 709, 420, 278, 47)
	XGUIEng.ShowWidget("OptionsMenuCppLogic_ToCppLogic", 1)
	CppLogic.UI.WidgetSetBaseData("OptionsMenuCppLogic_ToCppLogic", 5, false, false)
	CppLogic.UI.WidgetSetGroup("OptionsMenuCppLogic_ToCppLogic", "OptionGroup")
	XGUIEng.DisableButton("OptionsMenuCppLogic_ToCppLogic", 0)
	XGUIEng.HighLightButton("OptionsMenuCppLogic_ToCppLogic", 1)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenuCppLogic_ToCppLogic", 0, 0, 0, 1, 1)
	XGUIEng.SetMaterialTexture("OptionsMenuCppLogic_ToCppLogic", 0, "data\\graphics\\textures\\gui\\mainmenu\\right_button.png")
	XGUIEng.SetMaterialColor("OptionsMenuCppLogic_ToCppLogic", 0, 255, 255, 255, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenuCppLogic_ToCppLogic", 1, 0, 0, 1, 1)
	XGUIEng.SetMaterialTexture("OptionsMenuCppLogic_ToCppLogic", 1, "data\\graphics\\textures\\gui\\mainmenu\\right_button_hi.png")
	XGUIEng.SetMaterialColor("OptionsMenuCppLogic_ToCppLogic", 1, 255, 255, 255, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenuCppLogic_ToCppLogic", 2, 0, 0, 1, 1)
	XGUIEng.SetMaterialTexture("OptionsMenuCppLogic_ToCppLogic", 2, "data\\graphics\\textures\\gui\\mainmenu\\right_button_sel.png")
	XGUIEng.SetMaterialColor("OptionsMenuCppLogic_ToCppLogic", 2, 255, 255, 255, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenuCppLogic_ToCppLogic", 3, 0, 0, 1, 1)
	XGUIEng.SetMaterialTexture("OptionsMenuCppLogic_ToCppLogic", 3, "data\\graphics\\textures\\gui\\mainmenu\\right_button_in.png")
	XGUIEng.SetMaterialColor("OptionsMenuCppLogic_ToCppLogic", 3, 254, 254, 254, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenuCppLogic_ToCppLogic", 4, 0, 0, 1, 1)
	XGUIEng.SetMaterialTexture("OptionsMenuCppLogic_ToCppLogic", 4, "data\\graphics\\textures\\gui\\mainmenu\\right_button_akt.png")
	XGUIEng.SetMaterialColor("OptionsMenuCppLogic_ToCppLogic", 4, 255, 255, 255, 255)
	CppLogic.UI.WidgetSetTooltipData("OptionsMenuCppLogic_ToCppLogic", "StartMenu_TooltipText", true, true)
	CppLogic.UI.WidgetSetTooltipString("OptionsMenuCppLogic_ToCppLogic", "CppLogic_Mainmenu/ModPacksTT", true)
	CppLogic.UI.WidgetSetUpdateManualFlag("OptionsMenuCppLogic_ToCppLogic", true)
	CppLogic.UI.WidgetSetFont("OptionsMenuCppLogic_ToCppLogic", "data\\menu\\fonts\\mainmenularge.met")
	CppLogic.UI.WidgetSetStringFrameDistance("OptionsMenuCppLogic_ToCppLogic", 3)
	XGUIEng.SetTextKeyName("OptionsMenuCppLogic_ToCppLogic", "CppLogic_Mainmenu/ModPacksBTN")
	XGUIEng.SetTextColor("OptionsMenuCppLogic_ToCppLogic", 255, 255, 255, 255)
	CppLogic.UI.TextButtonSetCenterText("OptionsMenuCppLogic_ToCppLogic", true)
	CppLogic.UI.ContainerWidgetCreateStaticWidgetChild("OptionsMenuCppLogic", "OptionsMenuCppLogic_RightBG", nil)
	CppLogic.UI.WidgetSetPositionAndSize("OptionsMenuCppLogic_RightBG", 652, 0, 372, 768)
	XGUIEng.ShowWidget("OptionsMenuCppLogic_RightBG", 1)
	CppLogic.UI.WidgetSetBaseData("OptionsMenuCppLogic_RightBG", 1, false, false)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenuCppLogic_RightBG", 0, 0, 0, 1, 1)
	XGUIEng.SetMaterialTexture("OptionsMenuCppLogic_RightBG", 0, "data\\graphics\\textures\\gui\\mainmenu\\right_bg.png")
	XGUIEng.SetMaterialColor("OptionsMenuCppLogic_RightBG", 0, 255, 255, 255, 255)
	CppLogic.UI.ContainerWidgetCreateContainerWidgetChild("OptionsMenuCppLogic", "OptionsMenuCppLogic_MainContainer", nil)
	CppLogic.UI.WidgetSetPositionAndSize("OptionsMenuCppLogic_MainContainer", 0, 62, 732, 624)
	XGUIEng.ShowWidget("OptionsMenuCppLogic_MainContainer", 1)
	CppLogic.UI.WidgetSetBaseData("OptionsMenuCppLogic_MainContainer", 1, false, false)
	CppLogic.UI.ContainerWidgetCreateStaticTextWidgetChild("OptionsMenuCppLogic_MainContainer", "OptionsMenuCppLogic_Headline", nil)
	CppLogic.UI.WidgetSetPositionAndSize("OptionsMenuCppLogic_Headline", 33, 23, 200, 22)
	XGUIEng.ShowWidget("OptionsMenuCppLogic_Headline", 1)
	CppLogic.UI.WidgetSetBaseData("OptionsMenuCppLogic_Headline", 0, false, false)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenuCppLogic_Headline", 0, 0, 0, 1, 1)
	XGUIEng.SetMaterialColor("OptionsMenuCppLogic_Headline", 0, 0, 0, 0, 0)
	CppLogic.UI.WidgetSetFont("OptionsMenuCppLogic_Headline", "data\\menu\\fonts\\medium11bold.met")
	CppLogic.UI.WidgetSetStringFrameDistance("OptionsMenuCppLogic_Headline", 0)
	XGUIEng.SetTextKeyName("OptionsMenuCppLogic_Headline", "CppLogic_Mainmenu/ModPacksHead")
	XGUIEng.SetTextColor("OptionsMenuCppLogic_Headline", 255, 255, 255, 255)
	CppLogic.UI.WidgetSetUpdateManualFlag("OptionsMenuCppLogic_Headline", true)
	XGUIEng.SetLinesToPrint("OptionsMenuCppLogic_Headline", 0, 0)
	CppLogic.UI.StaticTextWidgetSetLineDistanceFactor("OptionsMenuCppLogic_Headline", 0)
	CppLogic.UI.ContainerWidgetCreateStaticTextWidgetChild("OptionsMenuCppLogic_MainContainer", "OptionsMenuCppLogic_SettingsHeadline", nil)
	CppLogic.UI.WidgetSetPositionAndSize("OptionsMenuCppLogic_SettingsHeadline", 300, 32, 300, 22)
	XGUIEng.ShowWidget("OptionsMenuCppLogic_SettingsHeadline", 1)
	CppLogic.UI.WidgetSetBaseData("OptionsMenuCppLogic_SettingsHeadline", 0, false, false)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenuCppLogic_SettingsHeadline", 0, 0, 0, 1, 1)
	XGUIEng.SetMaterialColor("OptionsMenuCppLogic_SettingsHeadline", 0, 0, 0, 0, 0)
	CppLogic.UI.WidgetSetFont("OptionsMenuCppLogic_SettingsHeadline", "data\\menu\\fonts\\medium11bold.met")
	CppLogic.UI.WidgetSetStringFrameDistance("OptionsMenuCppLogic_SettingsHeadline", 0)
	XGUIEng.SetTextKeyName("OptionsMenuCppLogic_SettingsHeadline", "CppLogic_Mainmenu/Settings")
	XGUIEng.SetTextColor("OptionsMenuCppLogic_SettingsHeadline", 255, 255, 255, 255)
	CppLogic.UI.WidgetSetUpdateManualFlag("OptionsMenuCppLogic_SettingsHeadline", true)
	XGUIEng.SetLinesToPrint("OptionsMenuCppLogic_SettingsHeadline", 0, 0)
	CppLogic.UI.StaticTextWidgetSetLineDistanceFactor("OptionsMenuCppLogic_SettingsHeadline", 0)
	CppLogic.UI.ContainerWidgetCreateContainerWidgetChild("OptionsMenuCppLogic_MainContainer", "OptionsMenuCppLogic_ModList", nil)
	CppLogic.UI.WidgetSetPositionAndSize("OptionsMenuCppLogic_ModList", 20, 50, 200, 400)
	XGUIEng.ShowWidget("OptionsMenuCppLogic_ModList", 1)
	CppLogic.UI.WidgetSetBaseData("OptionsMenuCppLogic_ModList", 0, false, false)
	CppLogic.UI.ContainerWidgetCreateContainerWidgetChild("OptionsMenuCppLogic_ModList", "OptionsMenuCppLogic_ModListList", nil)
	CppLogic.UI.WidgetSetPositionAndSize("OptionsMenuCppLogic_ModListList", 0, 25, 200, 400)
	XGUIEng.ShowWidget("OptionsMenuCppLogic_ModListList", 1)
	CppLogic.UI.WidgetSetBaseData("OptionsMenuCppLogic_ModListList", 0, false, false)
	CppLogic.UI.ContainerWidgetCreateTextButtonWidgetChild("OptionsMenuCppLogic_ModListList", "OptionsMenuCppLogic_ModListSelect", nil)
	CppLogic.UI.WidgetSetPositionAndSize("OptionsMenuCppLogic_ModListSelect", 0, 0, 200, 20)
	XGUIEng.ShowWidget("OptionsMenuCppLogic_ModListSelect", 1)
	CppLogic.UI.WidgetSetBaseData("OptionsMenuCppLogic_ModListSelect", 0, false, false)
	XGUIEng.DisableButton("OptionsMenuCppLogic_ModListSelect", 0)
	XGUIEng.HighLightButton("OptionsMenuCppLogic_ModListSelect", 0)
	CppLogic.UI.ButtonOverrideActionFunc("OptionsMenuCppLogic_ModListSelect", function()
		ModLoaderMainmenu.Scroll:GUIAction_DefaultSelect()
	end)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenuCppLogic_ModListSelect", 0, 0, 0, 1, 1)
	XGUIEng.SetMaterialColor("OptionsMenuCppLogic_ModListSelect", 0, 100, 100, 100, 131)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenuCppLogic_ModListSelect", 1, 0, 0, 1, 1)
	XGUIEng.SetMaterialColor("OptionsMenuCppLogic_ModListSelect", 1, 150, 150, 150, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenuCppLogic_ModListSelect", 2, 0, 0, 1, 1)
	XGUIEng.SetMaterialColor("OptionsMenuCppLogic_ModListSelect", 2, 255, 255, 255, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenuCppLogic_ModListSelect", 3, 0, 0, 1, 1)
	XGUIEng.SetMaterialColor("OptionsMenuCppLogic_ModListSelect", 3, 255, 255, 255, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenuCppLogic_ModListSelect", 4, 0, 0, 1, 1)
	XGUIEng.SetMaterialColor("OptionsMenuCppLogic_ModListSelect", 4, 255, 255, 255, 255)
	CppLogic.UI.WidgetSetTooltipData("OptionsMenuCppLogic_ModListSelect", nil, false, true)
	CppLogic.UI.WidgetSetUpdateManualFlag("OptionsMenuCppLogic_ModListSelect", false)
	CppLogic.UI.WidgetOverrideUpdateFunc("OptionsMenuCppLogic_ModListSelect", function()
		ModLoaderMainmenu.UpdateMod()
	end)
	CppLogic.UI.WidgetSetFont("OptionsMenuCppLogic_ModListSelect", "data\\menu\\fonts\\onscreen10.met")
	CppLogic.UI.WidgetSetStringFrameDistance("OptionsMenuCppLogic_ModListSelect", 0)
	XGUIEng.SetText("OptionsMenuCppLogic_ModListSelect", "@center name", 1)
	XGUIEng.SetTextColor("OptionsMenuCppLogic_ModListSelect", 255, 255, 255, 255)
	CppLogic.UI.TextButtonSetCenterText("OptionsMenuCppLogic_ModListSelect", true)
	CppLogic.UI.ContainerWidgetCreateCustomWidgetChild("OptionsMenuCppLogic_ModList", "OptionsMenuCppLogic_ModListScroll",
	                                                   "CppLogic::Mod::UI::AutoScrollCustomWidget", nil, 1, 0, 0, 0, 0, 0, "",
	                                                   "OptionsMenuCppLogic_ModListSelect")
	CppLogic.UI.WidgetSetPositionAndSize("OptionsMenuCppLogic_ModListScroll", 0, 25, 200, 400)
	XGUIEng.ShowWidget("OptionsMenuCppLogic_ModListScroll", 1)
	CppLogic.UI.WidgetSetBaseData("OptionsMenuCppLogic_ModListScroll", 0, false, false)
	CppLogic.UI.ContainerWidgetCreateContainerWidgetChild("OptionsMenuCppLogic_MainContainer", "OptionsMenuCppLogic_Settings", nil)
	CppLogic.UI.WidgetSetPositionAndSize("OptionsMenuCppLogic_Settings", 277, 65, 400, 400)
	XGUIEng.ShowWidget("OptionsMenuCppLogic_Settings", 1)
	CppLogic.UI.WidgetSetBaseData("OptionsMenuCppLogic_Settings", 0, false, false)
	CppLogic.UI.ContainerWidgetCreateTextButtonWidgetChild("OptionsMenuCppLogic_Settings", "OptionsMenuCppLogic_Settings_On", nil)
	CppLogic.UI.WidgetSetPositionAndSize("OptionsMenuCppLogic_Settings_On", 273, 13, 100, 47)
	XGUIEng.ShowWidget("OptionsMenuCppLogic_Settings_On", 1)
	CppLogic.UI.WidgetSetBaseData("OptionsMenuCppLogic_Settings_On", 0, false, false)
	XGUIEng.DisableButton("OptionsMenuCppLogic_Settings_On", 0)
	XGUIEng.HighLightButton("OptionsMenuCppLogic_Settings_On", 0)
	CppLogic.UI.ButtonOverrideActionFunc("OptionsMenuCppLogic_Settings_On", function()
		ModLoaderMainmenu.ActionActive()
	end)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenuCppLogic_Settings_On", 0, 0, 0, 1, 1)
	XGUIEng.SetMaterialTexture("OptionsMenuCppLogic_Settings_On", 0, "data\\graphics\\textures\\gui\\mainmenu\\sub.png")
	XGUIEng.SetMaterialColor("OptionsMenuCppLogic_Settings_On", 0, 255, 255, 255, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenuCppLogic_Settings_On", 1, 0, 0, 1, 1)
	XGUIEng.SetMaterialTexture("OptionsMenuCppLogic_Settings_On", 1, "data\\graphics\\textures\\gui\\mainmenu\\sub_hi.png")
	XGUIEng.SetMaterialColor("OptionsMenuCppLogic_Settings_On", 1, 255, 255, 255, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenuCppLogic_Settings_On", 2, 0, 0, 1, 1)
	XGUIEng.SetMaterialTexture("OptionsMenuCppLogic_Settings_On", 2, "data\\graphics\\textures\\gui\\mainmenu\\sub_sel.png")
	XGUIEng.SetMaterialColor("OptionsMenuCppLogic_Settings_On", 2, 255, 255, 255, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenuCppLogic_Settings_On", 3, 0, 0, 1, 1)
	XGUIEng.SetMaterialTexture("OptionsMenuCppLogic_Settings_On", 3, "data\\graphics\\textures\\gui\\mainmenu\\sub_in.png")
	XGUIEng.SetMaterialColor("OptionsMenuCppLogic_Settings_On", 3, 255, 255, 255, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenuCppLogic_Settings_On", 4, 0, 0, 1, 1)
	XGUIEng.SetMaterialTexture("OptionsMenuCppLogic_Settings_On", 4, "data\\graphics\\textures\\gui\\mainmenu\\sub_akt.png")
	XGUIEng.SetMaterialColor("OptionsMenuCppLogic_Settings_On", 4, 255, 255, 255, 255)
	CppLogic.UI.WidgetSetTooltipData("OptionsMenuCppLogic_Settings_On", "StartMenu_TooltipText", true, true)
	CppLogic.UI.WidgetSetTooltipString("OptionsMenuCppLogic_Settings_On", "CppLogic_Mainmenu/OnTT", true)
	CppLogic.UI.WidgetSetUpdateManualFlag("OptionsMenuCppLogic_Settings_On", false)
	CppLogic.UI.WidgetSetFont("OptionsMenuCppLogic_Settings_On", "data\\menu\\fonts\\mainmenularge.met")
	CppLogic.UI.WidgetSetStringFrameDistance("OptionsMenuCppLogic_Settings_On", 3)
	XGUIEng.SetTextKeyName("OptionsMenuCppLogic_Settings_On", "CppLogic_Mainmenu/On")
	XGUIEng.SetTextColor("OptionsMenuCppLogic_Settings_On", 255, 255, 255, 255)
	CppLogic.UI.TextButtonSetCenterText("OptionsMenuCppLogic_Settings_On", true)
	CppLogic.UI.ContainerWidgetCreateStaticTextWidgetChild("OptionsMenuCppLogic_Settings", "OptionsMenuCppLogic_Settings_Desc", nil)
	CppLogic.UI.WidgetSetPositionAndSize("OptionsMenuCppLogic_Settings_Desc", 16, 11, 246, 377)
	XGUIEng.ShowWidget("OptionsMenuCppLogic_Settings_Desc", 1)
	CppLogic.UI.WidgetSetBaseData("OptionsMenuCppLogic_Settings_Desc", 0, false, false)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenuCppLogic_Settings_Desc", 0, 0, 0, 1, 1)
	XGUIEng.SetMaterialColor("OptionsMenuCppLogic_Settings_Desc", 0, 0, 0, 0, 128)
	CppLogic.UI.WidgetSetFont("OptionsMenuCppLogic_Settings_Desc", "data\\menu\\fonts\\standard10.met")
	CppLogic.UI.WidgetSetStringFrameDistance("OptionsMenuCppLogic_Settings_Desc", 0)
	XGUIEng.SetText("OptionsMenuCppLogic_Settings_Desc", "", 1)
	XGUIEng.SetTextColor("OptionsMenuCppLogic_Settings_Desc", 255, 255, 255, 255)
	CppLogic.UI.WidgetSetUpdateManualFlag("OptionsMenuCppLogic_Settings_Desc", false)
	CppLogic.UI.WidgetOverrideUpdateFunc("OptionsMenuCppLogic_Settings_Desc", function()
		ModLoaderMainmenu.UpdateActive()
	end)
	XGUIEng.SetLinesToPrint("OptionsMenuCppLogic_Settings_Desc", 0, 0)
	CppLogic.UI.StaticTextWidgetSetLineDistanceFactor("OptionsMenuCppLogic_Settings_Desc", 0)
	CppLogic.UI.ContainerWidgetCreateTextButtonWidgetChild("OptionsMenuCppLogic_Settings", "OptionsMenuCppLogic_Settings_IG", nil)
	CppLogic.UI.WidgetSetPositionAndSize("OptionsMenuCppLogic_Settings_IG", 273, 63, 100, 47)
	XGUIEng.ShowWidget("OptionsMenuCppLogic_Settings_IG", 1)
	CppLogic.UI.WidgetSetBaseData("OptionsMenuCppLogic_Settings_IG", 0, false, false)
	XGUIEng.DisableButton("OptionsMenuCppLogic_Settings_IG", 0)
	XGUIEng.HighLightButton("OptionsMenuCppLogic_Settings_IG", 0)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenuCppLogic_Settings_IG", 0, 0, 0, 1, 1)
	XGUIEng.SetMaterialTexture("OptionsMenuCppLogic_Settings_IG", 0, "data\\graphics\\textures\\gui\\mainmenu\\sub.png")
	XGUIEng.SetMaterialColor("OptionsMenuCppLogic_Settings_IG", 0, 255, 255, 255, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenuCppLogic_Settings_IG", 1, 0, 0, 1, 1)
	XGUIEng.SetMaterialTexture("OptionsMenuCppLogic_Settings_IG", 1, "data\\graphics\\textures\\gui\\mainmenu\\sub_hi.png")
	XGUIEng.SetMaterialColor("OptionsMenuCppLogic_Settings_IG", 1, 255, 255, 255, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenuCppLogic_Settings_IG", 2, 0, 0, 1, 1)
	XGUIEng.SetMaterialTexture("OptionsMenuCppLogic_Settings_IG", 2, "data\\graphics\\textures\\gui\\mainmenu\\sub_sel.png")
	XGUIEng.SetMaterialColor("OptionsMenuCppLogic_Settings_IG", 2, 255, 255, 255, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenuCppLogic_Settings_IG", 3, 0, 0, 1, 1)
	XGUIEng.SetMaterialTexture("OptionsMenuCppLogic_Settings_IG", 3, "data\\graphics\\textures\\gui\\mainmenu\\sub_in.png")
	XGUIEng.SetMaterialColor("OptionsMenuCppLogic_Settings_IG", 3, 255, 255, 255, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenuCppLogic_Settings_IG", 4, 0, 0, 1, 1)
	XGUIEng.SetMaterialTexture("OptionsMenuCppLogic_Settings_IG", 4, "data\\graphics\\textures\\gui\\mainmenu\\sub_akt.png")
	XGUIEng.SetMaterialColor("OptionsMenuCppLogic_Settings_IG", 4, 255, 255, 255, 255)
	CppLogic.UI.WidgetSetTooltipData("OptionsMenuCppLogic_Settings_IG", "StartMenu_TooltipText", true, true)
	CppLogic.UI.WidgetSetTooltipString("OptionsMenuCppLogic_Settings_IG", "CppLogic_Mainmenu/IngameTT", true)
	CppLogic.UI.WidgetSetUpdateManualFlag("OptionsMenuCppLogic_Settings_IG", false)
	CppLogic.UI.WidgetSetFont("OptionsMenuCppLogic_Settings_IG", "data\\menu\\fonts\\mainmenularge.met")
	CppLogic.UI.WidgetSetStringFrameDistance("OptionsMenuCppLogic_Settings_IG", 3)
	XGUIEng.SetTextKeyName("OptionsMenuCppLogic_Settings_IG", "CppLogic_Mainmenu/Ingame")
	XGUIEng.SetTextColor("OptionsMenuCppLogic_Settings_IG", 255, 255, 255, 255)
	CppLogic.UI.TextButtonSetCenterText("OptionsMenuCppLogic_Settings_IG", true)
	CppLogic.UI.ContainerWidgetCreateTextButtonWidgetChild("OptionsMenuCppLogic_Settings", "OptionsMenuCppLogic_Settings_MM", nil)
	CppLogic.UI.WidgetSetPositionAndSize("OptionsMenuCppLogic_Settings_MM", 273, 113, 100, 47)
	XGUIEng.ShowWidget("OptionsMenuCppLogic_Settings_MM", 1)
	CppLogic.UI.WidgetSetBaseData("OptionsMenuCppLogic_Settings_MM", 0, false, false)
	XGUIEng.DisableButton("OptionsMenuCppLogic_Settings_MM", 0)
	XGUIEng.HighLightButton("OptionsMenuCppLogic_Settings_MM", 0)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenuCppLogic_Settings_MM", 0, 0, 0, 1, 1)
	XGUIEng.SetMaterialTexture("OptionsMenuCppLogic_Settings_MM", 0, "data\\graphics\\textures\\gui\\mainmenu\\sub.png")
	XGUIEng.SetMaterialColor("OptionsMenuCppLogic_Settings_MM", 0, 255, 255, 255, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenuCppLogic_Settings_MM", 1, 0, 0, 1, 1)
	XGUIEng.SetMaterialTexture("OptionsMenuCppLogic_Settings_MM", 1, "data\\graphics\\textures\\gui\\mainmenu\\sub_hi.png")
	XGUIEng.SetMaterialColor("OptionsMenuCppLogic_Settings_MM", 1, 255, 255, 255, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenuCppLogic_Settings_MM", 2, 0, 0, 1, 1)
	XGUIEng.SetMaterialTexture("OptionsMenuCppLogic_Settings_MM", 2, "data\\graphics\\textures\\gui\\mainmenu\\sub_sel.png")
	XGUIEng.SetMaterialColor("OptionsMenuCppLogic_Settings_MM", 2, 255, 255, 255, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenuCppLogic_Settings_MM", 3, 0, 0, 1, 1)
	XGUIEng.SetMaterialTexture("OptionsMenuCppLogic_Settings_MM", 3, "data\\graphics\\textures\\gui\\mainmenu\\sub_in.png")
	XGUIEng.SetMaterialColor("OptionsMenuCppLogic_Settings_MM", 3, 255, 255, 255, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenuCppLogic_Settings_MM", 4, 0, 0, 1, 1)
	XGUIEng.SetMaterialTexture("OptionsMenuCppLogic_Settings_MM", 4, "data\\graphics\\textures\\gui\\mainmenu\\sub_akt.png")
	XGUIEng.SetMaterialColor("OptionsMenuCppLogic_Settings_MM", 4, 255, 255, 255, 255)
	CppLogic.UI.WidgetSetTooltipData("OptionsMenuCppLogic_Settings_MM", "StartMenu_TooltipText", true, true)
	CppLogic.UI.WidgetSetTooltipString("OptionsMenuCppLogic_Settings_MM", "CppLogic_Mainmenu/MainmenuTT", true)
	CppLogic.UI.WidgetSetUpdateManualFlag("OptionsMenuCppLogic_Settings_MM", false)
	CppLogic.UI.WidgetSetFont("OptionsMenuCppLogic_Settings_MM", "data\\menu\\fonts\\mainmenularge.met")
	CppLogic.UI.WidgetSetStringFrameDistance("OptionsMenuCppLogic_Settings_MM", 3)
	XGUIEng.SetTextKeyName("OptionsMenuCppLogic_Settings_MM", "CppLogic_Mainmenu/Mainmenu")
	XGUIEng.SetTextColor("OptionsMenuCppLogic_Settings_MM", 255, 255, 255, 255)
	CppLogic.UI.TextButtonSetCenterText("OptionsMenuCppLogic_Settings_MM", true)
	CppLogic.UI.ContainerWidgetCreateContainerWidgetChild("OptionsMenuCppLogic_MainContainer", "OptionsMenuCppLogic_BG", nil)
	CppLogic.UI.WidgetSetPositionAndSize("OptionsMenuCppLogic_BG", 16, 10, 679, 474)
	XGUIEng.ShowWidget("OptionsMenuCppLogic_BG", 1)
	CppLogic.UI.WidgetSetBaseData("OptionsMenuCppLogic_BG", 0, false, false)
	CppLogic.UI.ContainerWidgetCreateStaticWidgetChild("OptionsMenuCppLogic_BG", "OptionsMenuCppLogic_BGShade", nil)
	CppLogic.UI.WidgetSetPositionAndSize("OptionsMenuCppLogic_BGShade", 0, 0, 679, 474)
	XGUIEng.ShowWidget("OptionsMenuCppLogic_BGShade", 1)
	CppLogic.UI.WidgetSetBaseData("OptionsMenuCppLogic_BGShade", 2, false, true)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenuCppLogic_BGShade", 0, 0, 0, 1, 1)
	XGUIEng.SetMaterialColor("OptionsMenuCppLogic_BGShade", 0, 0, 0, 0, 128)
	CppLogic.UI.ContainerWidgetCreateStaticWidgetChild("OptionsMenuCppLogic_BG", "OptionsMenuCppLogic_BGBottom", nil)
	CppLogic.UI.WidgetSetPositionAndSize("OptionsMenuCppLogic_BGBottom", 0, 473, 679, 1)
	XGUIEng.ShowWidget("OptionsMenuCppLogic_BGBottom", 1)
	CppLogic.UI.WidgetSetBaseData("OptionsMenuCppLogic_BGBottom", 0, false, true)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenuCppLogic_BGBottom", 0, 0, 0, 1, 1)
	XGUIEng.SetMaterialColor("OptionsMenuCppLogic_BGBottom", 0, 255, 255, 255, 255)
	CppLogic.UI.ContainerWidgetCreateStaticWidgetChild("OptionsMenuCppLogic_BG", "OptionsMenuCppLogic_BGFrameLeft", nil)
	CppLogic.UI.WidgetSetPositionAndSize("OptionsMenuCppLogic_BGFrameLeft", 0, 0, 1, 474)
	XGUIEng.ShowWidget("OptionsMenuCppLogic_BGFrameLeft", 1)
	CppLogic.UI.WidgetSetBaseData("OptionsMenuCppLogic_BGFrameLeft", 0, false, true)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenuCppLogic_BGFrameLeft", 0, 0, 0, 1, 1)
	XGUIEng.SetMaterialColor("OptionsMenuCppLogic_BGFrameLeft", 0, 255, 255, 255, 255)
	CppLogic.UI.ContainerWidgetCreateStaticWidgetChild("OptionsMenuCppLogic_BG", "OptionsMenuCppLogic_BGFrameRight", nil)
	CppLogic.UI.WidgetSetPositionAndSize("OptionsMenuCppLogic_BGFrameRight", 678, 0, 1, 474)
	XGUIEng.ShowWidget("OptionsMenuCppLogic_BGFrameRight", 1)
	CppLogic.UI.WidgetSetBaseData("OptionsMenuCppLogic_BGFrameRight", 0, false, true)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenuCppLogic_BGFrameRight", 0, 0, 0, 1, 1)
	XGUIEng.SetMaterialColor("OptionsMenuCppLogic_BGFrameRight", 0, 255, 255, 255, 255)
	CppLogic.UI.ContainerWidgetCreateStaticWidgetChild("OptionsMenuCppLogic_BG", "OptionsMenuCppLogic_BGTop", nil)
	CppLogic.UI.WidgetSetPositionAndSize("OptionsMenuCppLogic_BGTop", 0, 0, 679, 1)
	XGUIEng.ShowWidget("OptionsMenuCppLogic_BGTop", 1)
	CppLogic.UI.WidgetSetBaseData("OptionsMenuCppLogic_BGTop", 0, false, true)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenuCppLogic_BGTop", 0, 0, 0, 1, 1)
	XGUIEng.SetMaterialColor("OptionsMenuCppLogic_BGTop", 0, 255, 255, 255, 255)




	CppLogic.UI.WidgetSetPositionAndSize("OptionsMenu30_Resolution", 22, 277, 710, 247)


	if not CppLogic.UI.TextButtonSetCenterText then
		function CppLogic.UI.TextButtonSetCenterText() end
	end
	assert(XGUIEng.GetWidgetID("OptionsMenu30_ResExtra")==0, "OptionsMenu30_ResExtra already exists")
	assert(XGUIEng.GetWidgetID("OptionsMenu30_ResExtraList")==0, "OptionsMenu30_ResExtraList already exists")
	assert(XGUIEng.GetWidgetID("OptionsMenu30_ResExtraScrollableContainer")==0, "OptionsMenu30_ResExtraScrollableContainer already exists")
	assert(XGUIEng.GetWidgetID("OptionsMenu30_ResExtraScrollable")==0, "OptionsMenu30_ResExtraScrollable already exists")
	assert(XGUIEng.GetWidgetID("OptionsMenu30_ResExtraUp")==0, "OptionsMenu30_ResExtraUp already exists")
	assert(XGUIEng.GetWidgetID("OptionsMenu30_ResExtraDown")==0, "OptionsMenu30_ResExtraDown already exists")
	assert(XGUIEng.GetWidgetID("OptionsMenu30_ResExtraSliderBG")==0, "OptionsMenu30_ResExtraSliderBG already exists")
	assert(XGUIEng.GetWidgetID("OptionsMenu30_ResExtraScroll")==0, "OptionsMenu30_ResExtraScroll already exists")
	assert(XGUIEng.GetWidgetID("OptionsMenu30_ResExtraScrollBar")==0, "OptionsMenu30_ResExtraScrollBar already exists")
	assert(XGUIEng.GetWidgetID("OptionsMenu30_ResExtraSliderGfx")==0, "OptionsMenu30_ResExtraSliderGfx already exists")
	assert(XGUIEng.GetWidgetID("OptionsMenu30_ResExtra_BG")==0, "OptionsMenu30_ResExtra_BG already exists")
	assert(XGUIEng.GetWidgetID("OptionsMenu30_ResExtraToggle")==0, "OptionsMenu30_ResExtraToggle already exists")
	CppLogic.UI.ContainerWidgetCreateContainerWidgetChild("OptionsMenu30_Resolution", "OptionsMenu30_ResExtra", "OptionsMenu30_Resolution_Headline")
	CppLogic.UI.WidgetSetPositionAndSize("OptionsMenu30_ResExtra", 0, 0, 710, 247)
	XGUIEng.ShowWidget("OptionsMenu30_ResExtra", 1)
	CppLogic.UI.WidgetSetBaseData("OptionsMenu30_ResExtra", 0, false, false)
	CppLogic.UI.ContainerWidgetCreateContainerWidgetChild("OptionsMenu30_ResExtra", "OptionsMenu30_ResExtraList", nil)
	CppLogic.UI.WidgetSetPositionAndSize("OptionsMenu30_ResExtraList", 0, 20, 502, 207)
	XGUIEng.ShowWidget("OptionsMenu30_ResExtraList", 1)
	CppLogic.UI.WidgetSetBaseData("OptionsMenu30_ResExtraList", 10, false, false)
	CppLogic.UI.ContainerWidgetCreateContainerWidgetChild("OptionsMenu30_ResExtraList", "OptionsMenu30_ResExtraScrollableContainer", nil)
	CppLogic.UI.WidgetSetPositionAndSize("OptionsMenu30_ResExtraScrollableContainer", 6, 40, 491, 135)
	XGUIEng.ShowWidget("OptionsMenu30_ResExtraScrollableContainer", 1)
	CppLogic.UI.WidgetSetBaseData("OptionsMenu30_ResExtraScrollableContainer", 0, false, false)
	CppLogic.UI.ContainerWidgetCreateTextButtonWidgetChild("OptionsMenu30_ResExtraScrollableContainer", "OptionsMenu30_ResExtraScrollable", nil)
	CppLogic.UI.WidgetSetPositionAndSize("OptionsMenu30_ResExtraScrollable", 5, 46, 444, 20)
	XGUIEng.ShowWidget("OptionsMenu30_ResExtraScrollable", 1)
	CppLogic.UI.WidgetSetBaseData("OptionsMenu30_ResExtraScrollable", 0, false, false)
	XGUIEng.DisableButton("OptionsMenu30_ResExtraScrollable", 0)
	XGUIEng.HighLightButton("OptionsMenu30_ResExtraScrollable", 0)
	CppLogic.UI.ButtonOverrideActionFunc("OptionsMenu30_ResExtraScrollable", function() ModLoaderMainmenu.ActionMonitor() end)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenu30_ResExtraScrollable", 0, 0, 0, 1, 1)
	XGUIEng.SetMaterialColor("OptionsMenu30_ResExtraScrollable", 0, 151, 150, 151, 68)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenu30_ResExtraScrollable", 1, 0, 0, 1, 1)
	XGUIEng.SetMaterialColor("OptionsMenu30_ResExtraScrollable", 1, 250, 214, 121, 128)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenu30_ResExtraScrollable", 2, 0, 0, 1, 1)
	XGUIEng.SetMaterialColor("OptionsMenu30_ResExtraScrollable", 2, 150, 100, 50, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenu30_ResExtraScrollable", 3, 0, 0, 1, 1)
	XGUIEng.SetMaterialColor("OptionsMenu30_ResExtraScrollable", 3, 255, 255, 255, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenu30_ResExtraScrollable", 4, 0, 0, 1, 1)
	XGUIEng.SetMaterialColor("OptionsMenu30_ResExtraScrollable", 4, 220, 170, 120, 255)
	CppLogic.UI.WidgetSetTooltipData("OptionsMenu30_ResExtraScrollable", nil, false, false)
	CppLogic.UI.WidgetSetUpdateManualFlag("OptionsMenu30_ResExtraScrollable", false)
	CppLogic.UI.WidgetOverrideUpdateFunc("OptionsMenu30_ResExtraScrollable", function() ModLoaderMainmenu.UpdateMonitor() end)
	CppLogic.UI.WidgetSetFont("OptionsMenu30_ResExtraScrollable", "data\\menu\\fonts\\standard10.met")
	CppLogic.UI.WidgetSetStringFrameDistance("OptionsMenu30_ResExtraScrollable", 0)
	XGUIEng.SetText("OptionsMenu30_ResExtraScrollable", "", 1)
	XGUIEng.SetTextColor("OptionsMenu30_ResExtraScrollable", 255, 255, 255, 255)
	CppLogic.UI.TextButtonSetCenterText("OptionsMenu30_ResExtraScrollable", true)
	CppLogic.UI.ContainerWidgetCreateGFXButtonWidgetChild("OptionsMenu30_ResExtraList", "OptionsMenu30_ResExtraUp", nil)
	CppLogic.UI.WidgetSetPositionAndSize("OptionsMenu30_ResExtraUp", 468, 49, 31, 42)
	XGUIEng.ShowWidget("OptionsMenu30_ResExtraUp", 1)
	CppLogic.UI.WidgetSetBaseData("OptionsMenu30_ResExtraUp", 0, false, false)
	XGUIEng.DisableButton("OptionsMenu30_ResExtraUp", 0)
	XGUIEng.HighLightButton("OptionsMenu30_ResExtraUp", 0)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenu30_ResExtraUp", 0, 0, 0, 1, 1)
	XGUIEng.SetMaterialTexture("OptionsMenu30_ResExtraUp", 0, "data\\graphics\\textures\\gui\\mainmenu\\scroll_up.png")
	XGUIEng.SetMaterialColor("OptionsMenu30_ResExtraUp", 0, 255, 255, 255, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenu30_ResExtraUp", 1, 0, 0, 1, 1)
	XGUIEng.SetMaterialTexture("OptionsMenu30_ResExtraUp", 1, "data\\graphics\\textures\\gui\\mainmenu\\scroll_up_hi.png")
	XGUIEng.SetMaterialColor("OptionsMenu30_ResExtraUp", 1, 255, 255, 255, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenu30_ResExtraUp", 2, 0, 0, 1, 1)
	XGUIEng.SetMaterialTexture("OptionsMenu30_ResExtraUp", 2, "data\\graphics\\textures\\gui\\mainmenu\\scroll_up_sel.png")
	XGUIEng.SetMaterialColor("OptionsMenu30_ResExtraUp", 2, 255, 255, 255, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenu30_ResExtraUp", 3, 0, 0, 1, 1)
	XGUIEng.SetMaterialTexture("OptionsMenu30_ResExtraUp", 3, "data\\graphics\\textures\\gui\\mainmenu\\scroll_up.png")
	XGUIEng.SetMaterialColor("OptionsMenu30_ResExtraUp", 3, 128, 128, 128, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenu30_ResExtraUp", 4, 0, 0, 1, 1)
	XGUIEng.SetMaterialTexture("OptionsMenu30_ResExtraUp", 4, "data\\graphics\\textures\\gui\\mainmenu\\scroll_up.png")
	XGUIEng.SetMaterialColor("OptionsMenu30_ResExtraUp", 4, 255, 255, 255, 255)
	CppLogic.UI.WidgetSetTooltipData("OptionsMenu30_ResExtraUp", nil, false, true)
	CppLogic.UI.WidgetSetUpdateManualFlag("OptionsMenu30_ResExtraUp", false)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenu30_ResExtraUp", 10, 0, 0, 1, 1)
	XGUIEng.SetMaterialColor("OptionsMenu30_ResExtraUp", 10, 255, 255, 255, 0)
	CppLogic.UI.ContainerWidgetCreateGFXButtonWidgetChild("OptionsMenu30_ResExtraList", "OptionsMenu30_ResExtraDown", nil)
	CppLogic.UI.WidgetSetPositionAndSize("OptionsMenu30_ResExtraDown", 468, 128, 31, 45)
	XGUIEng.ShowWidget("OptionsMenu30_ResExtraDown", 1)
	CppLogic.UI.WidgetSetBaseData("OptionsMenu30_ResExtraDown", 0, false, false)
	XGUIEng.DisableButton("OptionsMenu30_ResExtraDown", 0)
	XGUIEng.HighLightButton("OptionsMenu30_ResExtraDown", 0)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenu30_ResExtraDown", 0, 0, 0, 1, 1)
	XGUIEng.SetMaterialTexture("OptionsMenu30_ResExtraDown", 0, "data\\graphics\\textures\\gui\\mainmenu\\scroll_down.png")
	XGUIEng.SetMaterialColor("OptionsMenu30_ResExtraDown", 0, 255, 255, 255, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenu30_ResExtraDown", 1, 0, 0, 1, 1)
	XGUIEng.SetMaterialTexture("OptionsMenu30_ResExtraDown", 1, "data\\graphics\\textures\\gui\\mainmenu\\scroll_down_hi.png")
	XGUIEng.SetMaterialColor("OptionsMenu30_ResExtraDown", 1, 255, 255, 255, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenu30_ResExtraDown", 2, 0, 0, 1, 1)
	XGUIEng.SetMaterialTexture("OptionsMenu30_ResExtraDown", 2, "data\\graphics\\textures\\gui\\mainmenu\\scroll_down_sel.png")
	XGUIEng.SetMaterialColor("OptionsMenu30_ResExtraDown", 2, 255, 255, 255, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenu30_ResExtraDown", 3, 0, 0, 1, 1)
	XGUIEng.SetMaterialTexture("OptionsMenu30_ResExtraDown", 3, "data\\graphics\\textures\\gui\\mainmenu\\scroll_down.png")
	XGUIEng.SetMaterialColor("OptionsMenu30_ResExtraDown", 3, 128, 128, 128, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenu30_ResExtraDown", 4, 0, 0, 1, 1)
	XGUIEng.SetMaterialTexture("OptionsMenu30_ResExtraDown", 4, "data\\graphics\\textures\\gui\\mainmenu\\scroll_down.png")
	XGUIEng.SetMaterialColor("OptionsMenu30_ResExtraDown", 4, 255, 255, 255, 255)
	CppLogic.UI.WidgetSetTooltipData("OptionsMenu30_ResExtraDown", nil, false, true)
	CppLogic.UI.WidgetSetUpdateManualFlag("OptionsMenu30_ResExtraDown", false)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenu30_ResExtraDown", 10, 0, 0, 1, 1)
	XGUIEng.SetMaterialColor("OptionsMenu30_ResExtraDown", 10, 255, 255, 255, 0)
	CppLogic.UI.ContainerWidgetCreateStaticWidgetChild("OptionsMenu30_ResExtraList", "OptionsMenu30_ResExtraSliderBG", nil)
	CppLogic.UI.WidgetSetPositionAndSize("OptionsMenu30_ResExtraSliderBG", 464, 46, 31, 123)
	XGUIEng.ShowWidget("OptionsMenu30_ResExtraSliderBG", 1)
	CppLogic.UI.WidgetSetBaseData("OptionsMenu30_ResExtraSliderBG", 0, false, true)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenu30_ResExtraSliderBG", 0, 0, 0, 1, 1)
	XGUIEng.SetMaterialTexture("OptionsMenu30_ResExtraSliderBG", 0, "data\\graphics\\textures\\gui\\mainmenu\\center_scroll_bg.png")
	XGUIEng.SetMaterialColor("OptionsMenu30_ResExtraSliderBG", 0, 255, 255, 255, 255)
	CppLogic.UI.ContainerWidgetCreateCustomWidgetChild("OptionsMenu30_ResExtraList", "OptionsMenu30_ResExtraScroll", "CppLogic::Mod::UI::AutoScrollCustomWidget", nil, 4, 0, 0, 0, 0, 0, "OptionsMenu30_ResExtraSliderGfx", "OptionsMenu30_ResExtraScrollable")
	CppLogic.UI.WidgetSetPositionAndSize("OptionsMenu30_ResExtraScroll", 0, 0, 502, 207)
	XGUIEng.ShowWidget("OptionsMenu30_ResExtraScroll", 1)
	CppLogic.UI.WidgetSetBaseData("OptionsMenu30_ResExtraScroll", 0, false, false)
	CppLogic.UI.ContainerWidgetCreateContainerWidgetChild("OptionsMenu30_ResExtraList", "OptionsMenu30_ResExtraScrollBar", nil)
	CppLogic.UI.WidgetSetPositionAndSize("OptionsMenu30_ResExtraScrollBar", 464, 84, 38, 44)
	XGUIEng.ShowWidget("OptionsMenu30_ResExtraScrollBar", 1)
	CppLogic.UI.WidgetSetBaseData("OptionsMenu30_ResExtraScrollBar", 0, false, false)
	CppLogic.UI.ContainerWidgetCreateStaticWidgetChild("OptionsMenu30_ResExtraScrollBar", "OptionsMenu30_ResExtraSliderGfx", nil)
	CppLogic.UI.WidgetSetPositionAndSize("OptionsMenu30_ResExtraSliderGfx", 4, 41, 23, 23)
	XGUIEng.ShowWidget("OptionsMenu30_ResExtraSliderGfx", 0)
	CppLogic.UI.WidgetSetBaseData("OptionsMenu30_ResExtraSliderGfx", 20, false, true)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenu30_ResExtraSliderGfx", 0, 0, 0, 1, 1)
	XGUIEng.SetMaterialTexture("OptionsMenu30_ResExtraSliderGfx", 0, "data\\graphics\\textures\\gui\\mainmenu\\scroll_handle.png")
	XGUIEng.SetMaterialColor("OptionsMenu30_ResExtraSliderGfx", 0, 255, 255, 255, 255)
	CppLogic.UI.ContainerWidgetCreateStaticWidgetChild("OptionsMenu30_ResExtraList", "OptionsMenu30_ResExtra_BG", nil)
	CppLogic.UI.WidgetSetPositionAndSize("OptionsMenu30_ResExtra_BG", 6, 40, 491, 135)
	XGUIEng.ShowWidget("OptionsMenu30_ResExtra_BG", 1)
	CppLogic.UI.WidgetSetBaseData("OptionsMenu30_ResExtra_BG", 0, false, true)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenu30_ResExtra_BG", 0, 0, 0, 1, 1)
	XGUIEng.SetMaterialColor("OptionsMenu30_ResExtra_BG", 0, 0, 7, 12, 96)
	CppLogic.UI.ContainerWidgetCreateTextButtonWidgetChild("OptionsMenu30_ResExtra", "OptionsMenu30_ResExtraToggle", nil)
	CppLogic.UI.WidgetSetPositionAndSize("OptionsMenu30_ResExtraToggle", 540, 64, 130, 47)
	XGUIEng.ShowWidget("OptionsMenu30_ResExtraToggle", 1)
	CppLogic.UI.WidgetSetBaseData("OptionsMenu30_ResExtraToggle", 0, false, false)
	XGUIEng.DisableButton("OptionsMenu30_ResExtraToggle", 0)
	XGUIEng.HighLightButton("OptionsMenu30_ResExtraToggle", 0)
	CppLogic.UI.ButtonOverrideActionFunc("OptionsMenu30_ResExtraToggle", function() ModLoaderMainmenu.ActionMonitorSelect() end)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenu30_ResExtraToggle", 0, 0, 0, 1, 1)
	XGUIEng.SetMaterialTexture("OptionsMenu30_ResExtraToggle", 0, "data\\graphics\\textures\\gui\\mainmenu\\sub.png")
	XGUIEng.SetMaterialColor("OptionsMenu30_ResExtraToggle", 0, 255, 255, 255, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenu30_ResExtraToggle", 1, 0, 0, 1, 1)
	XGUIEng.SetMaterialTexture("OptionsMenu30_ResExtraToggle", 1, "data\\graphics\\textures\\gui\\mainmenu\\sub_hi.png")
	XGUIEng.SetMaterialColor("OptionsMenu30_ResExtraToggle", 1, 255, 255, 255, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenu30_ResExtraToggle", 2, 0, 0, 1, 1)
	XGUIEng.SetMaterialTexture("OptionsMenu30_ResExtraToggle", 2, "data\\graphics\\textures\\gui\\mainmenu\\sub_sel.png")
	XGUIEng.SetMaterialColor("OptionsMenu30_ResExtraToggle", 2, 255, 255, 255, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenu30_ResExtraToggle", 3, 0, 0, 1, 1)
	XGUIEng.SetMaterialTexture("OptionsMenu30_ResExtraToggle", 3, "data\\graphics\\textures\\gui\\mainmenu\\sub_in.png")
	XGUIEng.SetMaterialColor("OptionsMenu30_ResExtraToggle", 3, 255, 255, 255, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenu30_ResExtraToggle", 4, 0, 0, 1, 1)
	XGUIEng.SetMaterialTexture("OptionsMenu30_ResExtraToggle", 4, "data\\graphics\\textures\\gui\\mainmenu\\sub_akt.png")
	XGUIEng.SetMaterialColor("OptionsMenu30_ResExtraToggle", 4, 255, 255, 255, 255)
	CppLogic.UI.WidgetSetTooltipData("OptionsMenu30_ResExtraToggle", "StartMenu_TooltipText", true, true)
	CppLogic.UI.WidgetSetTooltipString("OptionsMenu30_ResExtraToggle", "CppLogic_Mainmenu/BorderlessTT", true)
	CppLogic.UI.WidgetSetUpdateManualFlag("OptionsMenu30_ResExtraToggle", false)
	CppLogic.UI.WidgetOverrideUpdateFunc("OptionsMenu30_ResExtraToggle", function() ModLoaderMainmenu.UpdateMonitorSelect() end)
	CppLogic.UI.WidgetSetFont("OptionsMenu30_ResExtraToggle", "data\\menu\\fonts\\mainmenularge.met")
	CppLogic.UI.WidgetSetStringFrameDistance("OptionsMenu30_ResExtraToggle", 3)
	XGUIEng.SetTextKeyName("OptionsMenu30_ResExtraToggle", "CppLogic_Mainmenu/Borderless")
	XGUIEng.SetTextColor("OptionsMenu30_ResExtraToggle", 255, 255, 255, 255)
	CppLogic.UI.TextButtonSetCenterText("OptionsMenu30_ResExtraToggle", true)

end
