CppLogicOptions = {}

CppLogicOptions.S00_Start = OptionsMenu.S00_Start
---@diagnostic disable-next-line: duplicate-set-field
function OptionsMenu.S00_Start()
	if XGUIEng.GetWidgetID("OptionsMenuCppLogic") == 0 then
		CppLogicOptions.InitUI()
	end
	CppLogicOptions.S00_Start()
end

function CppLogicOptions.Show()
	XGUIEng.ShowAllSubWidgets("Screens", 0)
	XGUIEng.ShowWidget("OptionsMenuCppLogic", 1)
	CppLogicOptions.LoadModpacks()
end

function CppLogicOptions.LoadModpacks()
	CppLogicOptions.ModPacks = {}
	for _, m in ipairs(CppLogic.ModLoader.GetModpacks()) do
		local mp = CppLogic.ModLoader.GetModpackInfo(m)
		if type(mp) == "table" and mp.UserRequestable then
			table.insert(CppLogicOptions.ModPacks, {Name = mp.Name, Active = false})
		end
	end
	local str = GDB.GetString("CppLogic\\UserRequestedMods")
	if str and str ~= "" then
		for m in string.gfind(str, "([%w_/\\]+)") do
			for _, mp in ipairs(CppLogicOptions.ModPacks) do
				if mp.Name == m then
					mp.Active = true
				end
			end
		end
	end
	CppLogic.UI.InitAutoScrollCustomWidget("OptionsMenuCppLogic_ModListScroll", table.getn(CppLogicOptions.ModPacks))
end

function CppLogicOptions.StoreModpacks()
	local s = ""
	for _, mp in ipairs(CppLogicOptions.ModPacks) do
		if mp.Active then
			s = s..mp.Name..","
		end
	end
	GDB.SetString("CppLogic\\UserRequestedMods", s)
end

function CppLogicOptions.UpdateMod()
	local i = XGUIEng.GetBaseWidgetUserVariable(XGUIEng.GetCurrentWidgetID(), 0) + 1
	local mp = CppLogicOptions.ModPacks[i]
	XGUIEng.SetText(XGUIEng.GetCurrentWidgetID(), "@center " .. mp.Name)
	XGUIEng.HighLightButton(XGUIEng.GetCurrentWidgetID(), mp.Active and 1 or 0)
end

function CppLogicOptions.ActionMod()
	local i = XGUIEng.GetBaseWidgetUserVariable(XGUIEng.GetCurrentWidgetID(), 0) + 1
	local mp = CppLogicOptions.ModPacks[i]
	mp.Active = not mp.Active
	CppLogicOptions.StoreModpacks()
end

function CppLogicOptions.InitUI()
	if not CppLogic.UI.TextButtonSetCenterText then
		function CppLogic.UI.TextButtonSetCenterText() end
	end
	assert(XGUIEng.GetWidgetID("OptionsMenu10_ToCppLogic")==0, "OptionsMenu10_ToCppLogic already exists")
	CppLogic.UI.ContainerWidgetCreateTextButtonWidgetChild("OptionsMenu10", "OptionsMenu10_ToCppLogic", "OptionsMenu10_RightBG")
	CppLogic.UI.WidgetSetPositionAndSize("OptionsMenu10_ToCppLogic", 709, 420, 278, 47)
	XGUIEng.ShowWidget("OptionsMenu10_ToCppLogic", 1)
	CppLogic.UI.WidgetSetBaseData("OptionsMenu10_ToCppLogic", 5, false, false)
	CppLogic.UI.WidgetSetGroup("OptionsMenu10_ToCppLogic", "OptionGroup")
	XGUIEng.DisableButton("OptionsMenu10_ToCppLogic", 0)
	XGUIEng.HighLightButton("OptionsMenu10_ToCppLogic", 0)
	CppLogic.UI.ButtonOverrideActionFunc("OptionsMenu10_ToCppLogic", function() CppLogicOptions.Show() end)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenu10_ToCppLogic", 0, 0, 0, 1, 1)
	XGUIEng.SetMaterialTexture("OptionsMenu10_ToCppLogic", 0, "data\\graphics\\textures\\gui\\mainmenu\\right_button.png")
	XGUIEng.SetMaterialColor("OptionsMenu10_ToCppLogic", 0, 255, 255, 255, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenu10_ToCppLogic", 1, 0, 0, 1, 1)
	XGUIEng.SetMaterialTexture("OptionsMenu10_ToCppLogic", 1, "data\\graphics\\textures\\gui\\mainmenu\\right_button_hi.png")
	XGUIEng.SetMaterialColor("OptionsMenu10_ToCppLogic", 1, 255, 255, 255, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenu10_ToCppLogic", 2, 0, 0, 1, 1)
	XGUIEng.SetMaterialTexture("OptionsMenu10_ToCppLogic", 2, "data\\graphics\\textures\\gui\\mainmenu\\right_button_sel.png")
	XGUIEng.SetMaterialColor("OptionsMenu10_ToCppLogic", 2, 255, 255, 255, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenu10_ToCppLogic", 3, 0, 0, 1, 1)
	XGUIEng.SetMaterialTexture("OptionsMenu10_ToCppLogic", 3, "data\\graphics\\textures\\gui\\mainmenu\\right_button_in.png")
	XGUIEng.SetMaterialColor("OptionsMenu10_ToCppLogic", 3, 254, 254, 254, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenu10_ToCppLogic", 4, 0, 0, 1, 1)
	XGUIEng.SetMaterialTexture("OptionsMenu10_ToCppLogic", 4, "data\\graphics\\textures\\gui\\mainmenu\\right_button_akt.png")
	XGUIEng.SetMaterialColor("OptionsMenu10_ToCppLogic", 4, 255, 255, 255, 255)
	CppLogic.UI.WidgetSetTooltipData("OptionsMenu10_ToCppLogic", "StartMenu_TooltipText", true, true)
	CppLogic.UI.WidgetSetTooltipString("OptionsMenu10_ToCppLogic", "MainMenuTooltips/OptionsMenu00_ToNetwork", true)
	CppLogic.UI.WidgetSetUpdateManualFlag("OptionsMenu10_ToCppLogic", true)
	CppLogic.UI.WidgetSetFont("OptionsMenu10_ToCppLogic", "data\\menu\\fonts\\mainmenularge.met")
	CppLogic.UI.WidgetSetStringFrameDistance("OptionsMenu10_ToCppLogic", 3)
	XGUIEng.SetText("OptionsMenu10_ToCppLogic", "@center «ModPacks»", 1)
	XGUIEng.SetTextColor("OptionsMenu10_ToCppLogic", 255, 255, 255, 255)
	CppLogic.UI.TextButtonSetCenterText("OptionsMenu10_ToCppLogic", true)
	
	if not CppLogic.UI.TextButtonSetCenterText then
		function CppLogic.UI.TextButtonSetCenterText() end
	end
	assert(XGUIEng.GetWidgetID("OptionsMenu20_ToCppLogic")==0, "OptionsMenu20_ToCppLogic already exists")
	CppLogic.UI.ContainerWidgetCreateTextButtonWidgetChild("OptionsMenu20", "OptionsMenu20_ToCppLogic", "OptionsMenu20_RightBG")
	CppLogic.UI.WidgetSetPositionAndSize("OptionsMenu20_ToCppLogic", 709, 420, 278, 47)
	XGUIEng.ShowWidget("OptionsMenu20_ToCppLogic", 1)
	CppLogic.UI.WidgetSetBaseData("OptionsMenu20_ToCppLogic", 5, false, false)
	CppLogic.UI.WidgetSetGroup("OptionsMenu20_ToCppLogic", "OptionGroup")
	XGUIEng.DisableButton("OptionsMenu20_ToCppLogic", 0)
	XGUIEng.HighLightButton("OptionsMenu20_ToCppLogic", 0)
	CppLogic.UI.ButtonOverrideActionFunc("OptionsMenu20_ToCppLogic", function() CppLogicOptions.Show() end)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenu20_ToCppLogic", 0, 0, 0, 1, 1)
	XGUIEng.SetMaterialTexture("OptionsMenu20_ToCppLogic", 0, "data\\graphics\\textures\\gui\\mainmenu\\right_button.png")
	XGUIEng.SetMaterialColor("OptionsMenu20_ToCppLogic", 0, 255, 255, 255, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenu20_ToCppLogic", 1, 0, 0, 1, 1)
	XGUIEng.SetMaterialTexture("OptionsMenu20_ToCppLogic", 1, "data\\graphics\\textures\\gui\\mainmenu\\right_button_hi.png")
	XGUIEng.SetMaterialColor("OptionsMenu20_ToCppLogic", 1, 255, 255, 255, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenu20_ToCppLogic", 2, 0, 0, 1, 1)
	XGUIEng.SetMaterialTexture("OptionsMenu20_ToCppLogic", 2, "data\\graphics\\textures\\gui\\mainmenu\\right_button_sel.png")
	XGUIEng.SetMaterialColor("OptionsMenu20_ToCppLogic", 2, 255, 255, 255, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenu20_ToCppLogic", 3, 0, 0, 1, 1)
	XGUIEng.SetMaterialTexture("OptionsMenu20_ToCppLogic", 3, "data\\graphics\\textures\\gui\\mainmenu\\right_button_in.png")
	XGUIEng.SetMaterialColor("OptionsMenu20_ToCppLogic", 3, 254, 254, 254, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenu20_ToCppLogic", 4, 0, 0, 1, 1)
	XGUIEng.SetMaterialTexture("OptionsMenu20_ToCppLogic", 4, "data\\graphics\\textures\\gui\\mainmenu\\right_button_akt.png")
	XGUIEng.SetMaterialColor("OptionsMenu20_ToCppLogic", 4, 255, 255, 255, 255)
	CppLogic.UI.WidgetSetTooltipData("OptionsMenu20_ToCppLogic", "StartMenu_TooltipText", true, true)
	CppLogic.UI.WidgetSetTooltipString("OptionsMenu20_ToCppLogic", "MainMenuTooltips/OptionsMenu00_ToNetwork", true)
	CppLogic.UI.WidgetSetUpdateManualFlag("OptionsMenu20_ToCppLogic", true)
	CppLogic.UI.WidgetSetFont("OptionsMenu20_ToCppLogic", "data\\menu\\fonts\\mainmenularge.met")
	CppLogic.UI.WidgetSetStringFrameDistance("OptionsMenu20_ToCppLogic", 3)
	XGUIEng.SetText("OptionsMenu20_ToCppLogic", "@center «ModPacks»", 1)
	XGUIEng.SetTextColor("OptionsMenu20_ToCppLogic", 255, 255, 255, 255)
	CppLogic.UI.TextButtonSetCenterText("OptionsMenu20_ToCppLogic", true)
	
	if not CppLogic.UI.TextButtonSetCenterText then
		function CppLogic.UI.TextButtonSetCenterText() end
	end
	assert(XGUIEng.GetWidgetID("OptionsMenu30_ToCppLogic")==0, "OptionsMenu30_ToCppLogic already exists")
	CppLogic.UI.ContainerWidgetCreateTextButtonWidgetChild("OptionsMenu30", "OptionsMenu30_ToCppLogic", "OptionsMenu30_RightBG")
	CppLogic.UI.WidgetSetPositionAndSize("OptionsMenu30_ToCppLogic", 709, 420, 278, 47)
	XGUIEng.ShowWidget("OptionsMenu30_ToCppLogic", 1)
	CppLogic.UI.WidgetSetBaseData("OptionsMenu30_ToCppLogic", 5, false, false)
	CppLogic.UI.WidgetSetGroup("OptionsMenu30_ToCppLogic", "OptionGroup")
	XGUIEng.DisableButton("OptionsMenu30_ToCppLogic", 0)
	XGUIEng.HighLightButton("OptionsMenu30_ToCppLogic", 0)
	CppLogic.UI.ButtonOverrideActionFunc("OptionsMenu30_ToCppLogic", function() CppLogicOptions.Show() end)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenu30_ToCppLogic", 0, 0, 0, 1, 1)
	XGUIEng.SetMaterialTexture("OptionsMenu30_ToCppLogic", 0, "data\\graphics\\textures\\gui\\mainmenu\\right_button.png")
	XGUIEng.SetMaterialColor("OptionsMenu30_ToCppLogic", 0, 255, 255, 255, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenu30_ToCppLogic", 1, 0, 0, 1, 1)
	XGUIEng.SetMaterialTexture("OptionsMenu30_ToCppLogic", 1, "data\\graphics\\textures\\gui\\mainmenu\\right_button_hi.png")
	XGUIEng.SetMaterialColor("OptionsMenu30_ToCppLogic", 1, 255, 255, 255, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenu30_ToCppLogic", 2, 0, 0, 1, 1)
	XGUIEng.SetMaterialTexture("OptionsMenu30_ToCppLogic", 2, "data\\graphics\\textures\\gui\\mainmenu\\right_button_sel.png")
	XGUIEng.SetMaterialColor("OptionsMenu30_ToCppLogic", 2, 255, 255, 255, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenu30_ToCppLogic", 3, 0, 0, 1, 1)
	XGUIEng.SetMaterialTexture("OptionsMenu30_ToCppLogic", 3, "data\\graphics\\textures\\gui\\mainmenu\\right_button_in.png")
	XGUIEng.SetMaterialColor("OptionsMenu30_ToCppLogic", 3, 254, 254, 254, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenu30_ToCppLogic", 4, 0, 0, 1, 1)
	XGUIEng.SetMaterialTexture("OptionsMenu30_ToCppLogic", 4, "data\\graphics\\textures\\gui\\mainmenu\\right_button_akt.png")
	XGUIEng.SetMaterialColor("OptionsMenu30_ToCppLogic", 4, 255, 255, 255, 255)
	CppLogic.UI.WidgetSetTooltipData("OptionsMenu30_ToCppLogic", "StartMenu_TooltipText", true, true)
	CppLogic.UI.WidgetSetTooltipString("OptionsMenu30_ToCppLogic", "MainMenuTooltips/OptionsMenu00_ToNetwork", true)
	CppLogic.UI.WidgetSetUpdateManualFlag("OptionsMenu30_ToCppLogic", true)
	CppLogic.UI.WidgetSetFont("OptionsMenu30_ToCppLogic", "data\\menu\\fonts\\mainmenularge.met")
	CppLogic.UI.WidgetSetStringFrameDistance("OptionsMenu30_ToCppLogic", 3)
	XGUIEng.SetText("OptionsMenu30_ToCppLogic", "@center «ModPacks»", 1)
	XGUIEng.SetTextColor("OptionsMenu30_ToCppLogic", 255, 255, 255, 255)
	CppLogic.UI.TextButtonSetCenterText("OptionsMenu30_ToCppLogic", true)
	
	if not CppLogic.UI.TextButtonSetCenterText then
		function CppLogic.UI.TextButtonSetCenterText() end
	end
	assert(XGUIEng.GetWidgetID("OptionsMenu40_ToCppLogic")==0, "OptionsMenu40_ToCppLogic already exists")
	CppLogic.UI.ContainerWidgetCreateTextButtonWidgetChild("OptionsMenu40", "OptionsMenu40_ToCppLogic", "OptionsMenu40_RightBG")
	CppLogic.UI.WidgetSetPositionAndSize("OptionsMenu40_ToCppLogic", 709, 420, 278, 47)
	XGUIEng.ShowWidget("OptionsMenu40_ToCppLogic", 1)
	CppLogic.UI.WidgetSetBaseData("OptionsMenu40_ToCppLogic", 5, false, false)
	CppLogic.UI.WidgetSetGroup("OptionsMenu40_ToCppLogic", "OptionGroup")
	XGUIEng.DisableButton("OptionsMenu40_ToCppLogic", 0)
	XGUIEng.HighLightButton("OptionsMenu40_ToCppLogic", 0)
	CppLogic.UI.ButtonOverrideActionFunc("OptionsMenu40_ToCppLogic", function() CppLogicOptions.Show() end)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenu40_ToCppLogic", 0, 0, 0, 1, 1)
	XGUIEng.SetMaterialTexture("OptionsMenu40_ToCppLogic", 0, "data\\graphics\\textures\\gui\\mainmenu\\right_button.png")
	XGUIEng.SetMaterialColor("OptionsMenu40_ToCppLogic", 0, 255, 255, 255, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenu40_ToCppLogic", 1, 0, 0, 1, 1)
	XGUIEng.SetMaterialTexture("OptionsMenu40_ToCppLogic", 1, "data\\graphics\\textures\\gui\\mainmenu\\right_button_hi.png")
	XGUIEng.SetMaterialColor("OptionsMenu40_ToCppLogic", 1, 255, 255, 255, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenu40_ToCppLogic", 2, 0, 0, 1, 1)
	XGUIEng.SetMaterialTexture("OptionsMenu40_ToCppLogic", 2, "data\\graphics\\textures\\gui\\mainmenu\\right_button_sel.png")
	XGUIEng.SetMaterialColor("OptionsMenu40_ToCppLogic", 2, 255, 255, 255, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenu40_ToCppLogic", 3, 0, 0, 1, 1)
	XGUIEng.SetMaterialTexture("OptionsMenu40_ToCppLogic", 3, "data\\graphics\\textures\\gui\\mainmenu\\right_button_in.png")
	XGUIEng.SetMaterialColor("OptionsMenu40_ToCppLogic", 3, 254, 254, 254, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenu40_ToCppLogic", 4, 0, 0, 1, 1)
	XGUIEng.SetMaterialTexture("OptionsMenu40_ToCppLogic", 4, "data\\graphics\\textures\\gui\\mainmenu\\right_button_akt.png")
	XGUIEng.SetMaterialColor("OptionsMenu40_ToCppLogic", 4, 255, 255, 255, 255)
	CppLogic.UI.WidgetSetTooltipData("OptionsMenu40_ToCppLogic", "StartMenu_TooltipText", true, true)
	CppLogic.UI.WidgetSetTooltipString("OptionsMenu40_ToCppLogic", "MainMenuTooltips/OptionsMenu00_ToNetwork", true)
	CppLogic.UI.WidgetSetUpdateManualFlag("OptionsMenu40_ToCppLogic", true)
	CppLogic.UI.WidgetSetFont("OptionsMenu40_ToCppLogic", "data\\menu\\fonts\\mainmenularge.met")
	CppLogic.UI.WidgetSetStringFrameDistance("OptionsMenu40_ToCppLogic", 3)
	XGUIEng.SetText("OptionsMenu40_ToCppLogic", "@center «ModPacks»", 1)
	XGUIEng.SetTextColor("OptionsMenu40_ToCppLogic", 255, 255, 255, 255)
	CppLogic.UI.TextButtonSetCenterText("OptionsMenu40_ToCppLogic", true)
	
	if not CppLogic.UI.TextButtonSetCenterText then
		function CppLogic.UI.TextButtonSetCenterText() end
	end
	assert(XGUIEng.GetWidgetID("OptionsMenu50_ToCppLogic")==0, "OptionsMenu50_ToCppLogic already exists")
	CppLogic.UI.ContainerWidgetCreateTextButtonWidgetChild("OptionsMenu50", "OptionsMenu50_ToCppLogic", "OptionsMenu50_Connection_Modem")
	CppLogic.UI.WidgetSetPositionAndSize("OptionsMenu50_ToCppLogic", 709, 420, 278, 47)
	XGUIEng.ShowWidget("OptionsMenu50_ToCppLogic", 1)
	CppLogic.UI.WidgetSetBaseData("OptionsMenu50_ToCppLogic", 5, false, false)
	CppLogic.UI.WidgetSetGroup("OptionsMenu50_ToCppLogic", "OptionGroup")
	XGUIEng.DisableButton("OptionsMenu50_ToCppLogic", 0)
	XGUIEng.HighLightButton("OptionsMenu50_ToCppLogic", 0)
	CppLogic.UI.ButtonOverrideActionFunc("OptionsMenu50_ToCppLogic", function() CppLogicOptions.Show() end)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenu50_ToCppLogic", 0, 0, 0, 1, 1)
	XGUIEng.SetMaterialTexture("OptionsMenu50_ToCppLogic", 0, "data\\graphics\\textures\\gui\\mainmenu\\right_button.png")
	XGUIEng.SetMaterialColor("OptionsMenu50_ToCppLogic", 0, 255, 255, 255, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenu50_ToCppLogic", 1, 0, 0, 1, 1)
	XGUIEng.SetMaterialTexture("OptionsMenu50_ToCppLogic", 1, "data\\graphics\\textures\\gui\\mainmenu\\right_button_hi.png")
	XGUIEng.SetMaterialColor("OptionsMenu50_ToCppLogic", 1, 255, 255, 255, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenu50_ToCppLogic", 2, 0, 0, 1, 1)
	XGUIEng.SetMaterialTexture("OptionsMenu50_ToCppLogic", 2, "data\\graphics\\textures\\gui\\mainmenu\\right_button_sel.png")
	XGUIEng.SetMaterialColor("OptionsMenu50_ToCppLogic", 2, 255, 255, 255, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenu50_ToCppLogic", 3, 0, 0, 1, 1)
	XGUIEng.SetMaterialTexture("OptionsMenu50_ToCppLogic", 3, "data\\graphics\\textures\\gui\\mainmenu\\right_button_in.png")
	XGUIEng.SetMaterialColor("OptionsMenu50_ToCppLogic", 3, 254, 254, 254, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenu50_ToCppLogic", 4, 0, 0, 1, 1)
	XGUIEng.SetMaterialTexture("OptionsMenu50_ToCppLogic", 4, "data\\graphics\\textures\\gui\\mainmenu\\right_button_akt.png")
	XGUIEng.SetMaterialColor("OptionsMenu50_ToCppLogic", 4, 255, 255, 255, 255)
	CppLogic.UI.WidgetSetTooltipData("OptionsMenu50_ToCppLogic", "StartMenu_TooltipText", true, true)
	CppLogic.UI.WidgetSetTooltipString("OptionsMenu50_ToCppLogic", "MainMenuTooltips/OptionsMenu00_ToNetwork", true)
	CppLogic.UI.WidgetSetUpdateManualFlag("OptionsMenu50_ToCppLogic", true)
	CppLogic.UI.WidgetSetFont("OptionsMenu50_ToCppLogic", "data\\menu\\fonts\\mainmenularge.met")
	CppLogic.UI.WidgetSetStringFrameDistance("OptionsMenu50_ToCppLogic", 3)
	XGUIEng.SetText("OptionsMenu50_ToCppLogic", "@center «ModPacks»", 1)
	XGUIEng.SetTextColor("OptionsMenu50_ToCppLogic", 255, 255, 255, 255)
	CppLogic.UI.TextButtonSetCenterText("OptionsMenu50_ToCppLogic", true)
	
	if not CppLogic.UI.TextButtonSetCenterText then
		function CppLogic.UI.TextButtonSetCenterText() end
	end
	assert(XGUIEng.GetWidgetID("OptionsMenuCppLogic")==0, "OptionsMenuCppLogic already exists")
	assert(XGUIEng.GetWidgetID("OptionsMenuCppLogic_Back")==0, "OptionsMenuCppLogic_Back already exists")
	assert(XGUIEng.GetWidgetID("OptionsMenuCppLogic_ToControl")==0, "OptionsMenuCppLogic_ToControl already exists")
	assert(XGUIEng.GetWidgetID("OptionsMenuCppLogic_ToGraphics")==0, "OptionsMenuCppLogic_ToGraphics already exists")
	assert(XGUIEng.GetWidgetID("OptionsMenuCppLogic_ToNetwork")==0, "OptionsMenuCppLogic_ToNetwork already exists")
	assert(XGUIEng.GetWidgetID("OptionsMenuCppLogic_ToSound")==0, "OptionsMenuCppLogic_ToSound already exists")
	assert(XGUIEng.GetWidgetID("OptionsMenuCppLogic_ToUser")==0, "OptionsMenuCppLogic_ToUser already exists")
	assert(XGUIEng.GetWidgetID("OptionsMenuCppLogic_ToCppLogic")==0, "OptionsMenuCppLogic_ToCppLogic already exists")
	assert(XGUIEng.GetWidgetID("OptionsMenuCppLogic_RightBG")==0, "OptionsMenuCppLogic_RightBG already exists")
	assert(XGUIEng.GetWidgetID("OptionsMenuCppLogic_MainContainer")==0, "OptionsMenuCppLogic_MainContainer already exists")
	assert(XGUIEng.GetWidgetID("OptionsMenuCppLogic_Headline")==0, "OptionsMenuCppLogic_Headline already exists")
	assert(XGUIEng.GetWidgetID("OptionsMenuCppLogic_ModList")==0, "OptionsMenuCppLogic_ModList already exists")
	assert(XGUIEng.GetWidgetID("OptionsMenuCppLogic_ModListList")==0, "OptionsMenuCppLogic_ModListList already exists")
	assert(XGUIEng.GetWidgetID("OptionsMenuCppLogic_ModListSelect")==0, "OptionsMenuCppLogic_ModListSelect already exists")
	assert(XGUIEng.GetWidgetID("OptionsMenuCppLogic_ModListScroll")==0, "OptionsMenuCppLogic_ModListScroll already exists")
	assert(XGUIEng.GetWidgetID("OptionsMenuCppLogic_BG")==0, "OptionsMenuCppLogic_BG already exists")
	assert(XGUIEng.GetWidgetID("OptionsMenuCppLogic_BGShade")==0, "OptionsMenuCppLogic_BGShade already exists")
	assert(XGUIEng.GetWidgetID("OptionsMenuCppLogic_BGBottom")==0, "OptionsMenuCppLogic_BGBottom already exists")
	assert(XGUIEng.GetWidgetID("OptionsMenuCppLogic_BGFrameLeft")==0, "OptionsMenuCppLogic_BGFrameLeft already exists")
	assert(XGUIEng.GetWidgetID("OptionsMenuCppLogic_BGFrameRight")==0, "OptionsMenuCppLogic_BGFrameRight already exists")
	assert(XGUIEng.GetWidgetID("OptionsMenuCppLogic_BGTop")==0, "OptionsMenuCppLogic_BGTop already exists")
	CppLogic.UI.ContainerWidgetCreateContainerWidgetChild("Screens", "OptionsMenuCppLogic", nil)
	CppLogic.UI.WidgetSetPositionAndSize("OptionsMenuCppLogic", 0, 0, 1024, 768)
	XGUIEng.ShowWidget("OptionsMenuCppLogic", 0)
	CppLogic.UI.WidgetSetBaseData("OptionsMenuCppLogic", 0, false, false)
	CppLogic.UI.ContainerWidgetCreateTextButtonWidgetChild("OptionsMenuCppLogic", "OptionsMenuCppLogic_Back", nil)
	CppLogic.UI.WidgetSetPositionAndSize("OptionsMenuCppLogic_Back", 709, 500, 278, 47)
	XGUIEng.ShowWidget("OptionsMenuCppLogic_Back", 1)
	CppLogic.UI.WidgetSetBaseData("OptionsMenuCppLogic_Back", 5, false, false)
	XGUIEng.DisableButton("OptionsMenuCppLogic_Back", 0)
	XGUIEng.HighLightButton("OptionsMenuCppLogic_Back", 0)
	CppLogic.UI.ButtonOverrideActionFunc("OptionsMenuCppLogic_Back", function() OptionsMenu.S00_Button_ToStart() end)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenuCppLogic_Back", 0, 0, 0, 1, 1)
	XGUIEng.SetMaterialTexture("OptionsMenuCppLogic_Back", 0, "data\\graphics\\textures\\gui\\mainmenu\\right_button.png")
	XGUIEng.SetMaterialColor("OptionsMenuCppLogic_Back", 0, 255, 255, 255, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenuCppLogic_Back", 1, 0, 0, 1, 1)
	XGUIEng.SetMaterialTexture("OptionsMenuCppLogic_Back", 1, "data\\graphics\\textures\\gui\\mainmenu\\right_button_hi.png")
	XGUIEng.SetMaterialColor("OptionsMenuCppLogic_Back", 1, 255, 255, 255, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenuCppLogic_Back", 2, 0, 0, 1, 1)
	XGUIEng.SetMaterialTexture("OptionsMenuCppLogic_Back", 2, "data\\graphics\\textures\\gui\\mainmenu\\right_button_sel.png")
	XGUIEng.SetMaterialColor("OptionsMenuCppLogic_Back", 2, 255, 255, 255, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenuCppLogic_Back", 3, 0, 0, 1, 1)
	XGUIEng.SetMaterialTexture("OptionsMenuCppLogic_Back", 3, "data\\graphics\\textures\\gui\\mainmenu\\right_button_in.png")
	XGUIEng.SetMaterialColor("OptionsMenuCppLogic_Back", 3, 254, 254, 254, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenuCppLogic_Back", 4, 0, 0, 1, 1)
	XGUIEng.SetMaterialTexture("OptionsMenuCppLogic_Back", 4, "data\\graphics\\textures\\gui\\mainmenu\\right_button_akt.png")
	XGUIEng.SetMaterialColor("OptionsMenuCppLogic_Back", 4, 255, 255, 255, 255)
	CppLogic.UI.WidgetSetTooltipData("OptionsMenuCppLogic_Back", "StartMenu_TooltipText", true, true)
	CppLogic.UI.WidgetSetTooltipString("OptionsMenuCppLogic_Back", "MainMenuTooltips/OptionsMenu00_Back", true)
	CppLogic.UI.WidgetSetUpdateManualFlag("OptionsMenuCppLogic_Back", true)
	CppLogic.UI.WidgetSetFont("OptionsMenuCppLogic_Back", "data\\menu\\fonts\\mainmenularge.met")
	CppLogic.UI.WidgetSetStringFrameDistance("OptionsMenuCppLogic_Back", 3)
	XGUIEng.SetTextKeyName("OptionsMenuCppLogic_Back", "MainMenu/Back")
	XGUIEng.SetTextColor("OptionsMenuCppLogic_Back", 255, 255, 255, 255)
	CppLogic.UI.TextButtonSetCenterText("OptionsMenuCppLogic_Back", true)
	CppLogic.UI.ContainerWidgetCreateTextButtonWidgetChild("OptionsMenuCppLogic", "OptionsMenuCppLogic_ToControl", nil)
	CppLogic.UI.WidgetSetPositionAndSize("OptionsMenuCppLogic_ToControl", 709, 220, 278, 47)
	XGUIEng.ShowWidget("OptionsMenuCppLogic_ToControl", 1)
	CppLogic.UI.WidgetSetBaseData("OptionsMenuCppLogic_ToControl", 5, false, false)
	CppLogic.UI.WidgetSetGroup("OptionsMenuCppLogic_ToControl", "OptionGroup")
	XGUIEng.DisableButton("OptionsMenuCppLogic_ToControl", 0)
	XGUIEng.HighLightButton("OptionsMenuCppLogic_ToControl", 0)
	CppLogic.UI.ButtonOverrideActionFunc("OptionsMenuCppLogic_ToControl", function() OptionsMenu.S20_Start() end)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenuCppLogic_ToControl", 0, 0, 0, 1, 1)
	XGUIEng.SetMaterialTexture("OptionsMenuCppLogic_ToControl", 0, "data\\graphics\\textures\\gui\\mainmenu\\right_button.png")
	XGUIEng.SetMaterialColor("OptionsMenuCppLogic_ToControl", 0, 255, 255, 255, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenuCppLogic_ToControl", 1, 0, 0, 1, 1)
	XGUIEng.SetMaterialTexture("OptionsMenuCppLogic_ToControl", 1, "data\\graphics\\textures\\gui\\mainmenu\\right_button_hi.png")
	XGUIEng.SetMaterialColor("OptionsMenuCppLogic_ToControl", 1, 255, 255, 255, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenuCppLogic_ToControl", 2, 0, 0, 1, 1)
	XGUIEng.SetMaterialTexture("OptionsMenuCppLogic_ToControl", 2, "data\\graphics\\textures\\gui\\mainmenu\\right_button_sel.png")
	XGUIEng.SetMaterialColor("OptionsMenuCppLogic_ToControl", 2, 255, 255, 255, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenuCppLogic_ToControl", 3, 0, 0, 1, 1)
	XGUIEng.SetMaterialTexture("OptionsMenuCppLogic_ToControl", 3, "data\\graphics\\textures\\gui\\mainmenu\\right_button_in.png")
	XGUIEng.SetMaterialColor("OptionsMenuCppLogic_ToControl", 3, 254, 254, 254, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenuCppLogic_ToControl", 4, 0, 0, 1, 1)
	XGUIEng.SetMaterialTexture("OptionsMenuCppLogic_ToControl", 4, "data\\graphics\\textures\\gui\\mainmenu\\right_button_akt.png")
	XGUIEng.SetMaterialColor("OptionsMenuCppLogic_ToControl", 4, 255, 255, 255, 255)
	CppLogic.UI.WidgetSetTooltipData("OptionsMenuCppLogic_ToControl", "StartMenu_TooltipText", true, true)
	CppLogic.UI.WidgetSetTooltipString("OptionsMenuCppLogic_ToControl", "MainMenuTooltips/OptionsMenu00_ToControl", true)
	CppLogic.UI.WidgetSetUpdateManualFlag("OptionsMenuCppLogic_ToControl", true)
	CppLogic.UI.WidgetSetFont("OptionsMenuCppLogic_ToControl", "data\\menu\\fonts\\mainmenularge.met")
	CppLogic.UI.WidgetSetStringFrameDistance("OptionsMenuCppLogic_ToControl", 3)
	XGUIEng.SetTextKeyName("OptionsMenuCppLogic_ToControl", "MainMenu/Options_Controls")
	XGUIEng.SetTextColor("OptionsMenuCppLogic_ToControl", 255, 255, 255, 255)
	CppLogic.UI.TextButtonSetCenterText("OptionsMenuCppLogic_ToControl", true)
	CppLogic.UI.ContainerWidgetCreateTextButtonWidgetChild("OptionsMenuCppLogic", "OptionsMenuCppLogic_ToGraphics", nil)
	CppLogic.UI.WidgetSetPositionAndSize("OptionsMenuCppLogic_ToGraphics", 709, 270, 278, 47)
	XGUIEng.ShowWidget("OptionsMenuCppLogic_ToGraphics", 1)
	CppLogic.UI.WidgetSetBaseData("OptionsMenuCppLogic_ToGraphics", 5, false, false)
	CppLogic.UI.WidgetSetGroup("OptionsMenuCppLogic_ToGraphics", "OptionGroup")
	XGUIEng.DisableButton("OptionsMenuCppLogic_ToGraphics", 0)
	XGUIEng.HighLightButton("OptionsMenuCppLogic_ToGraphics", 0)
	CppLogic.UI.ButtonOverrideActionFunc("OptionsMenuCppLogic_ToGraphics", function() OptionsMenu.S30_Start() end)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenuCppLogic_ToGraphics", 0, 0, 0, 1, 1)
	XGUIEng.SetMaterialTexture("OptionsMenuCppLogic_ToGraphics", 0, "data\\graphics\\textures\\gui\\mainmenu\\right_button.png")
	XGUIEng.SetMaterialColor("OptionsMenuCppLogic_ToGraphics", 0, 255, 255, 255, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenuCppLogic_ToGraphics", 1, 0, 0, 1, 1)
	XGUIEng.SetMaterialTexture("OptionsMenuCppLogic_ToGraphics", 1, "data\\graphics\\textures\\gui\\mainmenu\\right_button_hi.png")
	XGUIEng.SetMaterialColor("OptionsMenuCppLogic_ToGraphics", 1, 255, 255, 255, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenuCppLogic_ToGraphics", 2, 0, 0, 1, 1)
	XGUIEng.SetMaterialTexture("OptionsMenuCppLogic_ToGraphics", 2, "data\\graphics\\textures\\gui\\mainmenu\\right_button_sel.png")
	XGUIEng.SetMaterialColor("OptionsMenuCppLogic_ToGraphics", 2, 255, 255, 255, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenuCppLogic_ToGraphics", 3, 0, 0, 1, 1)
	XGUIEng.SetMaterialTexture("OptionsMenuCppLogic_ToGraphics", 3, "data\\graphics\\textures\\gui\\mainmenu\\right_button_in.png")
	XGUIEng.SetMaterialColor("OptionsMenuCppLogic_ToGraphics", 3, 254, 254, 254, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenuCppLogic_ToGraphics", 4, 0, 0, 1, 1)
	XGUIEng.SetMaterialTexture("OptionsMenuCppLogic_ToGraphics", 4, "data\\graphics\\textures\\gui\\mainmenu\\right_button_akt.png")
	XGUIEng.SetMaterialColor("OptionsMenuCppLogic_ToGraphics", 4, 255, 255, 255, 255)
	CppLogic.UI.WidgetSetTooltipData("OptionsMenuCppLogic_ToGraphics", "StartMenu_TooltipText", true, true)
	CppLogic.UI.WidgetSetTooltipString("OptionsMenuCppLogic_ToGraphics", "MainMenuTooltips/OptionsMenu00_ToGraphics", true)
	CppLogic.UI.WidgetSetUpdateManualFlag("OptionsMenuCppLogic_ToGraphics", true)
	CppLogic.UI.WidgetSetFont("OptionsMenuCppLogic_ToGraphics", "data\\menu\\fonts\\mainmenularge.met")
	CppLogic.UI.WidgetSetStringFrameDistance("OptionsMenuCppLogic_ToGraphics", 3)
	XGUIEng.SetTextKeyName("OptionsMenuCppLogic_ToGraphics", "MainMenu/Options_Graphics")
	XGUIEng.SetTextColor("OptionsMenuCppLogic_ToGraphics", 255, 255, 255, 255)
	CppLogic.UI.TextButtonSetCenterText("OptionsMenuCppLogic_ToGraphics", true)
	CppLogic.UI.ContainerWidgetCreateTextButtonWidgetChild("OptionsMenuCppLogic", "OptionsMenuCppLogic_ToNetwork", nil)
	CppLogic.UI.WidgetSetPositionAndSize("OptionsMenuCppLogic_ToNetwork", 709, 370, 278, 47)
	XGUIEng.ShowWidget("OptionsMenuCppLogic_ToNetwork", 1)
	CppLogic.UI.WidgetSetBaseData("OptionsMenuCppLogic_ToNetwork", 5, false, false)
	CppLogic.UI.WidgetSetGroup("OptionsMenuCppLogic_ToNetwork", "OptionGroup")
	XGUIEng.DisableButton("OptionsMenuCppLogic_ToNetwork", 0)
	XGUIEng.HighLightButton("OptionsMenuCppLogic_ToNetwork", 0)
	CppLogic.UI.ButtonOverrideActionFunc("OptionsMenuCppLogic_ToNetwork", function() OptionsMenu.S50_Start() end)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenuCppLogic_ToNetwork", 0, 0, 0, 1, 1)
	XGUIEng.SetMaterialTexture("OptionsMenuCppLogic_ToNetwork", 0, "data\\graphics\\textures\\gui\\mainmenu\\right_button.png")
	XGUIEng.SetMaterialColor("OptionsMenuCppLogic_ToNetwork", 0, 255, 255, 255, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenuCppLogic_ToNetwork", 1, 0, 0, 1, 1)
	XGUIEng.SetMaterialTexture("OptionsMenuCppLogic_ToNetwork", 1, "data\\graphics\\textures\\gui\\mainmenu\\right_button_hi.png")
	XGUIEng.SetMaterialColor("OptionsMenuCppLogic_ToNetwork", 1, 255, 255, 255, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenuCppLogic_ToNetwork", 2, 0, 0, 1, 1)
	XGUIEng.SetMaterialTexture("OptionsMenuCppLogic_ToNetwork", 2, "data\\graphics\\textures\\gui\\mainmenu\\right_button_sel.png")
	XGUIEng.SetMaterialColor("OptionsMenuCppLogic_ToNetwork", 2, 255, 255, 255, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenuCppLogic_ToNetwork", 3, 0, 0, 1, 1)
	XGUIEng.SetMaterialTexture("OptionsMenuCppLogic_ToNetwork", 3, "data\\graphics\\textures\\gui\\mainmenu\\right_button_in.png")
	XGUIEng.SetMaterialColor("OptionsMenuCppLogic_ToNetwork", 3, 254, 254, 254, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenuCppLogic_ToNetwork", 4, 0, 0, 1, 1)
	XGUIEng.SetMaterialTexture("OptionsMenuCppLogic_ToNetwork", 4, "data\\graphics\\textures\\gui\\mainmenu\\right_button_akt.png")
	XGUIEng.SetMaterialColor("OptionsMenuCppLogic_ToNetwork", 4, 255, 255, 255, 255)
	CppLogic.UI.WidgetSetTooltipData("OptionsMenuCppLogic_ToNetwork", "StartMenu_TooltipText", true, true)
	CppLogic.UI.WidgetSetTooltipString("OptionsMenuCppLogic_ToNetwork", "MainMenuTooltips/OptionsMenu00_ToNetwork", true)
	CppLogic.UI.WidgetSetUpdateManualFlag("OptionsMenuCppLogic_ToNetwork", true)
	CppLogic.UI.WidgetSetFont("OptionsMenuCppLogic_ToNetwork", "data\\menu\\fonts\\mainmenularge.met")
	CppLogic.UI.WidgetSetStringFrameDistance("OptionsMenuCppLogic_ToNetwork", 3)
	XGUIEng.SetTextKeyName("OptionsMenuCppLogic_ToNetwork", "MainMenu/Options_Network")
	XGUIEng.SetTextColor("OptionsMenuCppLogic_ToNetwork", 255, 255, 255, 255)
	CppLogic.UI.TextButtonSetCenterText("OptionsMenuCppLogic_ToNetwork", true)
	CppLogic.UI.ContainerWidgetCreateTextButtonWidgetChild("OptionsMenuCppLogic", "OptionsMenuCppLogic_ToSound", nil)
	CppLogic.UI.WidgetSetPositionAndSize("OptionsMenuCppLogic_ToSound", 709, 320, 278, 47)
	XGUIEng.ShowWidget("OptionsMenuCppLogic_ToSound", 1)
	CppLogic.UI.WidgetSetBaseData("OptionsMenuCppLogic_ToSound", 5, false, false)
	CppLogic.UI.WidgetSetGroup("OptionsMenuCppLogic_ToSound", "OptionGroup")
	XGUIEng.DisableButton("OptionsMenuCppLogic_ToSound", 0)
	XGUIEng.HighLightButton("OptionsMenuCppLogic_ToSound", 0)
	CppLogic.UI.ButtonOverrideActionFunc("OptionsMenuCppLogic_ToSound", function() OptionsMenu.S40_Start() end)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenuCppLogic_ToSound", 0, 0, 0, 1, 1)
	XGUIEng.SetMaterialTexture("OptionsMenuCppLogic_ToSound", 0, "data\\graphics\\textures\\gui\\mainmenu\\right_button.png")
	XGUIEng.SetMaterialColor("OptionsMenuCppLogic_ToSound", 0, 255, 255, 255, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenuCppLogic_ToSound", 1, 0, 0, 1, 1)
	XGUIEng.SetMaterialTexture("OptionsMenuCppLogic_ToSound", 1, "data\\graphics\\textures\\gui\\mainmenu\\right_button_hi.png")
	XGUIEng.SetMaterialColor("OptionsMenuCppLogic_ToSound", 1, 255, 255, 255, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenuCppLogic_ToSound", 2, 0, 0, 1, 1)
	XGUIEng.SetMaterialTexture("OptionsMenuCppLogic_ToSound", 2, "data\\graphics\\textures\\gui\\mainmenu\\right_button_sel.png")
	XGUIEng.SetMaterialColor("OptionsMenuCppLogic_ToSound", 2, 255, 255, 255, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenuCppLogic_ToSound", 3, 0, 0, 1, 1)
	XGUIEng.SetMaterialTexture("OptionsMenuCppLogic_ToSound", 3, "data\\graphics\\textures\\gui\\mainmenu\\right_button_in.png")
	XGUIEng.SetMaterialColor("OptionsMenuCppLogic_ToSound", 3, 254, 254, 254, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenuCppLogic_ToSound", 4, 0, 0, 1, 1)
	XGUIEng.SetMaterialTexture("OptionsMenuCppLogic_ToSound", 4, "data\\graphics\\textures\\gui\\mainmenu\\right_button_akt.png")
	XGUIEng.SetMaterialColor("OptionsMenuCppLogic_ToSound", 4, 255, 255, 255, 255)
	CppLogic.UI.WidgetSetTooltipData("OptionsMenuCppLogic_ToSound", "StartMenu_TooltipText", true, true)
	CppLogic.UI.WidgetSetTooltipString("OptionsMenuCppLogic_ToSound", "MainMenuTooltips/OptionsMenu00_ToSound", true)
	CppLogic.UI.WidgetSetUpdateManualFlag("OptionsMenuCppLogic_ToSound", true)
	CppLogic.UI.WidgetSetFont("OptionsMenuCppLogic_ToSound", "data\\menu\\fonts\\mainmenularge.met")
	CppLogic.UI.WidgetSetStringFrameDistance("OptionsMenuCppLogic_ToSound", 3)
	XGUIEng.SetTextKeyName("OptionsMenuCppLogic_ToSound", "MainMenu/Options_Sound")
	XGUIEng.SetTextColor("OptionsMenuCppLogic_ToSound", 255, 255, 255, 255)
	CppLogic.UI.TextButtonSetCenterText("OptionsMenuCppLogic_ToSound", true)
	CppLogic.UI.ContainerWidgetCreateTextButtonWidgetChild("OptionsMenuCppLogic", "OptionsMenuCppLogic_ToUser", nil)
	CppLogic.UI.WidgetSetPositionAndSize("OptionsMenuCppLogic_ToUser", 709, 170, 278, 47)
	XGUIEng.ShowWidget("OptionsMenuCppLogic_ToUser", 1)
	CppLogic.UI.WidgetSetBaseData("OptionsMenuCppLogic_ToUser", 5, false, false)
	CppLogic.UI.WidgetSetGroup("OptionsMenuCppLogic_ToUser", "OptionGroup")
	XGUIEng.DisableButton("OptionsMenuCppLogic_ToUser", 0)
	XGUIEng.HighLightButton("OptionsMenuCppLogic_ToUser", 0)
	CppLogic.UI.ButtonOverrideActionFunc("OptionsMenuCppLogic_ToUser", function() OptionsMenu.S10_Start() end)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenuCppLogic_ToUser", 0, 0, 0, 1, 1)
	XGUIEng.SetMaterialTexture("OptionsMenuCppLogic_ToUser", 0, "data\\graphics\\textures\\gui\\mainmenu\\right_button.png")
	XGUIEng.SetMaterialColor("OptionsMenuCppLogic_ToUser", 0, 255, 255, 255, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenuCppLogic_ToUser", 1, 0, 0, 1, 1)
	XGUIEng.SetMaterialTexture("OptionsMenuCppLogic_ToUser", 1, "data\\graphics\\textures\\gui\\mainmenu\\right_button_hi.png")
	XGUIEng.SetMaterialColor("OptionsMenuCppLogic_ToUser", 1, 255, 255, 255, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenuCppLogic_ToUser", 2, 0, 0, 1, 1)
	XGUIEng.SetMaterialTexture("OptionsMenuCppLogic_ToUser", 2, "data\\graphics\\textures\\gui\\mainmenu\\right_button_sel.png")
	XGUIEng.SetMaterialColor("OptionsMenuCppLogic_ToUser", 2, 255, 255, 255, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenuCppLogic_ToUser", 3, 0, 0, 1, 1)
	XGUIEng.SetMaterialTexture("OptionsMenuCppLogic_ToUser", 3, "data\\graphics\\textures\\gui\\mainmenu\\right_button_in.png")
	XGUIEng.SetMaterialColor("OptionsMenuCppLogic_ToUser", 3, 254, 254, 254, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenuCppLogic_ToUser", 4, 0, 0, 1, 1)
	XGUIEng.SetMaterialTexture("OptionsMenuCppLogic_ToUser", 4, "data\\graphics\\textures\\gui\\mainmenu\\right_button_akt.png")
	XGUIEng.SetMaterialColor("OptionsMenuCppLogic_ToUser", 4, 255, 255, 255, 255)
	CppLogic.UI.WidgetSetTooltipData("OptionsMenuCppLogic_ToUser", "StartMenu_TooltipText", true, true)
	CppLogic.UI.WidgetSetTooltipString("OptionsMenuCppLogic_ToUser", "MainMenuTooltips/OptionsMenu00_ToUser", true)
	CppLogic.UI.WidgetSetUpdateManualFlag("OptionsMenuCppLogic_ToUser", true)
	CppLogic.UI.WidgetSetFont("OptionsMenuCppLogic_ToUser", "data\\menu\\fonts\\mainmenularge.met")
	CppLogic.UI.WidgetSetStringFrameDistance("OptionsMenuCppLogic_ToUser", 3)
	XGUIEng.SetTextKeyName("OptionsMenuCppLogic_ToUser", "MainMenu/Options_User")
	XGUIEng.SetTextColor("OptionsMenuCppLogic_ToUser", 255, 255, 255, 255)
	CppLogic.UI.TextButtonSetCenterText("OptionsMenuCppLogic_ToUser", true)
	CppLogic.UI.ContainerWidgetCreateTextButtonWidgetChild("OptionsMenuCppLogic", "OptionsMenuCppLogic_ToCppLogic", nil)
	CppLogic.UI.WidgetSetPositionAndSize("OptionsMenuCppLogic_ToCppLogic", 709, 420, 278, 47)
	XGUIEng.ShowWidget("OptionsMenuCppLogic_ToCppLogic", 1)
	CppLogic.UI.WidgetSetBaseData("OptionsMenuCppLogic_ToCppLogic", 5, false, false)
	CppLogic.UI.WidgetSetGroup("OptionsMenuCppLogic_ToCppLogic", "OptionGroup")
	XGUIEng.DisableButton("OptionsMenuCppLogic_ToCppLogic", 0)
	XGUIEng.HighLightButton("OptionsMenuCppLogic_ToCppLogic", 1)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenuCppLogic_ToCppLogic", 0, 0, 0, 1, 1)
	XGUIEng.SetMaterialTexture("OptionsMenuCppLogic_ToCppLogic", 0, "data\\graphics\\textures\\gui\\mainmenu\\right_button.png")
	XGUIEng.SetMaterialColor("OptionsMenuCppLogic_ToCppLogic", 0, 255, 255, 255, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenuCppLogic_ToCppLogic", 1, 0, 0, 1, 1)
	XGUIEng.SetMaterialTexture("OptionsMenuCppLogic_ToCppLogic", 1, "data\\graphics\\textures\\gui\\mainmenu\\right_button_hi.png")
	XGUIEng.SetMaterialColor("OptionsMenuCppLogic_ToCppLogic", 1, 255, 255, 255, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenuCppLogic_ToCppLogic", 2, 0, 0, 1, 1)
	XGUIEng.SetMaterialTexture("OptionsMenuCppLogic_ToCppLogic", 2, "data\\graphics\\textures\\gui\\mainmenu\\right_button_sel.png")
	XGUIEng.SetMaterialColor("OptionsMenuCppLogic_ToCppLogic", 2, 255, 255, 255, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenuCppLogic_ToCppLogic", 3, 0, 0, 1, 1)
	XGUIEng.SetMaterialTexture("OptionsMenuCppLogic_ToCppLogic", 3, "data\\graphics\\textures\\gui\\mainmenu\\right_button_in.png")
	XGUIEng.SetMaterialColor("OptionsMenuCppLogic_ToCppLogic", 3, 254, 254, 254, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenuCppLogic_ToCppLogic", 4, 0, 0, 1, 1)
	XGUIEng.SetMaterialTexture("OptionsMenuCppLogic_ToCppLogic", 4, "data\\graphics\\textures\\gui\\mainmenu\\right_button_akt.png")
	XGUIEng.SetMaterialColor("OptionsMenuCppLogic_ToCppLogic", 4, 255, 255, 255, 255)
	CppLogic.UI.WidgetSetTooltipData("OptionsMenuCppLogic_ToCppLogic", "StartMenu_TooltipText", true, true)
	CppLogic.UI.WidgetSetTooltipString("OptionsMenuCppLogic_ToCppLogic", "MainMenuTooltips/OptionsMenu00_ToNetwork", true)
	CppLogic.UI.WidgetSetUpdateManualFlag("OptionsMenuCppLogic_ToCppLogic", true)
	CppLogic.UI.WidgetSetFont("OptionsMenuCppLogic_ToCppLogic", "data\\menu\\fonts\\mainmenularge.met")
	CppLogic.UI.WidgetSetStringFrameDistance("OptionsMenuCppLogic_ToCppLogic", 3)
	XGUIEng.SetText("OptionsMenuCppLogic_ToCppLogic", "@center «ModPacks»", 1)
	XGUIEng.SetTextColor("OptionsMenuCppLogic_ToCppLogic", 255, 255, 255, 255)
	CppLogic.UI.TextButtonSetCenterText("OptionsMenuCppLogic_ToCppLogic", true)
	CppLogic.UI.ContainerWidgetCreateStaticWidgetChild("OptionsMenuCppLogic", "OptionsMenuCppLogic_RightBG", nil)
	CppLogic.UI.WidgetSetPositionAndSize("OptionsMenuCppLogic_RightBG", 652, 0, 372, 768)
	XGUIEng.ShowWidget("OptionsMenuCppLogic_RightBG", 1)
	CppLogic.UI.WidgetSetBaseData("OptionsMenuCppLogic_RightBG", 1, false, false)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenuCppLogic_RightBG", 0, 0, 0, 1, 1)
	XGUIEng.SetMaterialTexture("OptionsMenuCppLogic_RightBG", 0, "data\\graphics\\textures\\gui\\mainmenu\\right_bg.png")
	XGUIEng.SetMaterialColor("OptionsMenuCppLogic_RightBG", 0, 255, 255, 255, 255)
	CppLogic.UI.ContainerWidgetCreateContainerWidgetChild("OptionsMenuCppLogic", "OptionsMenuCppLogic_MainContainer", nil)
	CppLogic.UI.WidgetSetPositionAndSize("OptionsMenuCppLogic_MainContainer", 0, 62, 732, 624)
	XGUIEng.ShowWidget("OptionsMenuCppLogic_MainContainer", 1)
	CppLogic.UI.WidgetSetBaseData("OptionsMenuCppLogic_MainContainer", 1, false, false)
	CppLogic.UI.ContainerWidgetCreateStaticTextWidgetChild("OptionsMenuCppLogic_MainContainer", "OptionsMenuCppLogic_Headline", nil)
	CppLogic.UI.WidgetSetPositionAndSize("OptionsMenuCppLogic_Headline", 33, 23, 300, 22)
	XGUIEng.ShowWidget("OptionsMenuCppLogic_Headline", 1)
	CppLogic.UI.WidgetSetBaseData("OptionsMenuCppLogic_Headline", 1, false, false)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenuCppLogic_Headline", 0, 0, 0, 1, 1)
	XGUIEng.SetMaterialColor("OptionsMenuCppLogic_Headline", 0, 0, 0, 0, 0)
	CppLogic.UI.WidgetSetFont("OptionsMenuCppLogic_Headline", "data\\menu\\fonts\\medium11bold.met")
	CppLogic.UI.WidgetSetStringFrameDistance("OptionsMenuCppLogic_Headline", 0)
	XGUIEng.SetText("OptionsMenuCppLogic_Headline", "selected modpacks:", 1)
	XGUIEng.SetTextColor("OptionsMenuCppLogic_Headline", 255, 255, 255, 255)
	CppLogic.UI.WidgetSetUpdateManualFlag("OptionsMenuCppLogic_Headline", true)
	XGUIEng.SetLinesToPrint("OptionsMenuCppLogic_Headline", 0, 0)
	CppLogic.UI.StaticTextWidgetSetLineDistanceFactor("OptionsMenuCppLogic_Headline", 0)
	CppLogic.UI.ContainerWidgetCreateContainerWidgetChild("OptionsMenuCppLogic_MainContainer", "OptionsMenuCppLogic_ModList", nil)
	CppLogic.UI.WidgetSetPositionAndSize("OptionsMenuCppLogic_ModList", 20, 50, 200, 400)
	XGUIEng.ShowWidget("OptionsMenuCppLogic_ModList", 1)
	CppLogic.UI.WidgetSetBaseData("OptionsMenuCppLogic_ModList", 0, false, false)
	CppLogic.UI.ContainerWidgetCreateContainerWidgetChild("OptionsMenuCppLogic_ModList", "OptionsMenuCppLogic_ModListList", nil)
	CppLogic.UI.WidgetSetPositionAndSize("OptionsMenuCppLogic_ModListList", 0, 25, 200, 400)
	XGUIEng.ShowWidget("OptionsMenuCppLogic_ModListList", 1)
	CppLogic.UI.WidgetSetBaseData("OptionsMenuCppLogic_ModListList", 0, false, false)
	CppLogic.UI.ContainerWidgetCreateTextButtonWidgetChild("OptionsMenuCppLogic_ModListList", "OptionsMenuCppLogic_ModListSelect", nil)
	CppLogic.UI.WidgetSetPositionAndSize("OptionsMenuCppLogic_ModListSelect", 0, 0, 200, 20)
	XGUIEng.ShowWidget("OptionsMenuCppLogic_ModListSelect", 1)
	CppLogic.UI.WidgetSetBaseData("OptionsMenuCppLogic_ModListSelect", 0, false, false)
	XGUIEng.DisableButton("OptionsMenuCppLogic_ModListSelect", 0)
	XGUIEng.HighLightButton("OptionsMenuCppLogic_ModListSelect", 0)
	CppLogic.UI.ButtonOverrideActionFunc("OptionsMenuCppLogic_ModListSelect", function() CppLogicOptions.ActionMod() end)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenuCppLogic_ModListSelect", 0, 0, 0, 1, 1)
	XGUIEng.SetMaterialColor("OptionsMenuCppLogic_ModListSelect", 0, 100, 100, 100, 131)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenuCppLogic_ModListSelect", 1, 0, 0, 1, 1)
	XGUIEng.SetMaterialColor("OptionsMenuCppLogic_ModListSelect", 1, 150, 150, 150, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenuCppLogic_ModListSelect", 2, 0, 0, 1, 1)
	XGUIEng.SetMaterialColor("OptionsMenuCppLogic_ModListSelect", 2, 255, 255, 255, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenuCppLogic_ModListSelect", 3, 0, 0, 1, 1)
	XGUIEng.SetMaterialColor("OptionsMenuCppLogic_ModListSelect", 3, 255, 255, 255, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenuCppLogic_ModListSelect", 4, 0, 0, 1, 1)
	XGUIEng.SetMaterialColor("OptionsMenuCppLogic_ModListSelect", 4, 255, 255, 255, 255)
	CppLogic.UI.WidgetSetTooltipData("OptionsMenuCppLogic_ModListSelect", nil, false, true)
	CppLogic.UI.WidgetSetUpdateManualFlag("OptionsMenuCppLogic_ModListSelect", false)
	CppLogic.UI.WidgetOverrideUpdateFunc("OptionsMenuCppLogic_ModListSelect", function() CppLogicOptions.UpdateMod() end)
	CppLogic.UI.WidgetSetFont("OptionsMenuCppLogic_ModListSelect", "data\\menu\\fonts\\onscreen10.met")
	CppLogic.UI.WidgetSetStringFrameDistance("OptionsMenuCppLogic_ModListSelect", 0)
	XGUIEng.SetText("OptionsMenuCppLogic_ModListSelect", "@center name", 1)
	XGUIEng.SetTextColor("OptionsMenuCppLogic_ModListSelect", 255, 255, 255, 255)
	CppLogic.UI.TextButtonSetCenterText("OptionsMenuCppLogic_ModListSelect", true)
	CppLogic.UI.ContainerWidgetCreateCustomWidgetChild("OptionsMenuCppLogic_ModList", "OptionsMenuCppLogic_ModListScroll", "CppLogic::Mod::UI::AutoScrollCustomWidget", nil, 1, 0, 0, 0, 0, 0, "", "OptionsMenuCppLogic_ModListSelect")
	CppLogic.UI.WidgetSetPositionAndSize("OptionsMenuCppLogic_ModListScroll", 0, 25, 200, 400)
	XGUIEng.ShowWidget("OptionsMenuCppLogic_ModListScroll", 1)
	CppLogic.UI.WidgetSetBaseData("OptionsMenuCppLogic_ModListScroll", 0, false, false)
	CppLogic.UI.ContainerWidgetCreateContainerWidgetChild("OptionsMenuCppLogic_MainContainer", "OptionsMenuCppLogic_BG", nil)
	CppLogic.UI.WidgetSetPositionAndSize("OptionsMenuCppLogic_BG", 16, 10, 679, 474)
	XGUIEng.ShowWidget("OptionsMenuCppLogic_BG", 1)
	CppLogic.UI.WidgetSetBaseData("OptionsMenuCppLogic_BG", 0, false, false)
	CppLogic.UI.ContainerWidgetCreateStaticWidgetChild("OptionsMenuCppLogic_BG", "OptionsMenuCppLogic_BGShade", nil)
	CppLogic.UI.WidgetSetPositionAndSize("OptionsMenuCppLogic_BGShade", 0, 0, 679, 474)
	XGUIEng.ShowWidget("OptionsMenuCppLogic_BGShade", 1)
	CppLogic.UI.WidgetSetBaseData("OptionsMenuCppLogic_BGShade", 2, false, true)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenuCppLogic_BGShade", 0, 0, 0, 1, 1)
	XGUIEng.SetMaterialColor("OptionsMenuCppLogic_BGShade", 0, 0, 0, 0, 128)
	CppLogic.UI.ContainerWidgetCreateStaticWidgetChild("OptionsMenuCppLogic_BG", "OptionsMenuCppLogic_BGBottom", nil)
	CppLogic.UI.WidgetSetPositionAndSize("OptionsMenuCppLogic_BGBottom", 0, 473, 679, 1)
	XGUIEng.ShowWidget("OptionsMenuCppLogic_BGBottom", 1)
	CppLogic.UI.WidgetSetBaseData("OptionsMenuCppLogic_BGBottom", 0, false, true)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenuCppLogic_BGBottom", 0, 0, 0, 1, 1)
	XGUIEng.SetMaterialColor("OptionsMenuCppLogic_BGBottom", 0, 255, 255, 255, 255)
	CppLogic.UI.ContainerWidgetCreateStaticWidgetChild("OptionsMenuCppLogic_BG", "OptionsMenuCppLogic_BGFrameLeft", nil)
	CppLogic.UI.WidgetSetPositionAndSize("OptionsMenuCppLogic_BGFrameLeft", 0, 0, 1, 474)
	XGUIEng.ShowWidget("OptionsMenuCppLogic_BGFrameLeft", 1)
	CppLogic.UI.WidgetSetBaseData("OptionsMenuCppLogic_BGFrameLeft", 0, false, true)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenuCppLogic_BGFrameLeft", 0, 0, 0, 1, 1)
	XGUIEng.SetMaterialColor("OptionsMenuCppLogic_BGFrameLeft", 0, 255, 255, 255, 255)
	CppLogic.UI.ContainerWidgetCreateStaticWidgetChild("OptionsMenuCppLogic_BG", "OptionsMenuCppLogic_BGFrameRight", nil)
	CppLogic.UI.WidgetSetPositionAndSize("OptionsMenuCppLogic_BGFrameRight", 678, 0, 1, 474)
	XGUIEng.ShowWidget("OptionsMenuCppLogic_BGFrameRight", 1)
	CppLogic.UI.WidgetSetBaseData("OptionsMenuCppLogic_BGFrameRight", 0, false, true)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenuCppLogic_BGFrameRight", 0, 0, 0, 1, 1)
	XGUIEng.SetMaterialColor("OptionsMenuCppLogic_BGFrameRight", 0, 255, 255, 255, 255)
	CppLogic.UI.ContainerWidgetCreateStaticWidgetChild("OptionsMenuCppLogic_BG", "OptionsMenuCppLogic_BGTop", nil)
	CppLogic.UI.WidgetSetPositionAndSize("OptionsMenuCppLogic_BGTop", 0, 0, 679, 1)
	XGUIEng.ShowWidget("OptionsMenuCppLogic_BGTop", 1)
	CppLogic.UI.WidgetSetBaseData("OptionsMenuCppLogic_BGTop", 0, false, true)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("OptionsMenuCppLogic_BGTop", 0, 0, 0, 1, 1)
	XGUIEng.SetMaterialColor("OptionsMenuCppLogic_BGTop", 0, 255, 255, 255, 255)
	
end
